### ISSUE TITLE
send password in API function for new user just once

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/api#106]
Please look at https://github.com/Tendrl/api/pull/103/files#r106957463

**Comment by anivargi** [comment]
@mkudlej can you clarify what you mean exactly?

**Comment by fbalak** [comment]
I think that this issue should be open. It doesn't seem right to send `password_confirmation` parameter via api during user creation. Check for same passwords should be done on the frontend side.

**Comment by shirshendu** [comment]
https://github.com/Tendrl/ui/issues/859 can be implemented once this issue is closed.
