### ISSUE TITLE
Flows API call returns empty array

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#114]
Flows should return list of possible API calls with parameters, it returns empty list instead.

```
# curl -X GET -i -k -H "Authorization: Bearer <token>" <hostname>/api/1.0/Flows; echo ""
HTTP/1.1 200 OK
Date: Thu, 23 Mar 2017 12:59:57 GMT
Server: Apache/2.4.6 (CentOS) mod_wsgi/3.4 Python/2.7.5
Content-Type: application/json
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE
Access-Control-Allow-Headers: Origin,Content-Type,Accept,Authorization,X-Requested-With
X-Content-Type-Options: nosniff
Content-Length: 12

{"flows":[]}
```

Used Packages:
tendrl-api-1.2.1-03_22_2017_17_03_14.noarch
tendrl-dashboard-1.2.1-03_23_2017_04_29_50.noarch
tendrl-commons-1.2.1-03_23_2017_12_30_14.noarch
tendrl-api-doc-1.2.1-03_22_2017_17_03_14.noarch
tendrl-performance-monitoring-1.2.1-03_22_2017_16_43_46.noarch
tendrl-api-httpd-1.2.1-03_22_2017_17_03_14.noarch

**Comment by anivargi** [comment]
The definitions files are changed and hence they return no Flows.

**Comment by ltrilety** [comment]
Tested on:
tendrl-api-1.2.1-04_03_2017_01_51_03.noarch
tendrl-dashboard-1.2.1-04_03_2017_04_11_02.noarch
tendrl-api-doc-1.2.1-04_03_2017_01_51_03.noarch
tendrl-performance-monitoring-1.2.1-04_03_2017_03_02_04.noarch
tendrl-api-httpd-1.2.1-04_03_2017_01_51_03.noarch
tendrl-commons-1.2.1-04_01_2017_00_59_17.noarch

There are two API calls present in `Flows` response: `CreateCluster` and `ImportCluster`
