### ISSUE TITLE
[security] Tendrl API would logout wrong user session or prevent sesstion to logout caused by shared global access token handling

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#118]
## Description

When single Tendrl user opens multiple sessions to Tendrl API server, one session could either be logged out by another session or another session could prevent the 1st session to log out properly.

This severely breaks user expectations about the core functionality of how login works.

Note: it seems almost impossible to avoid hitting this issue in real world deployments because Tendrl Dashboard (web ui) also uses Tendrl API - so user doesn't even need to open multiple session to trigger this bug, opening a API session while using web interface would be enough. 

## Versions of Related Components

```
# rpm -qa tendrl-*
tendrl-api-1.2.1-03_27_2017_01_51_03.noarch
tendrl-dashboard-1.2.1-03_27_2017_04_11_05.noarch
tendrl-api-doc-1.2.1-03_27_2017_01_51_03.noarch
tendrl-performance-monitoring-1.2.1-03_27_2017_18_50_12.noarch
tendrl-api-httpd-1.2.1-03_27_2017_01_51_03.noarch
tendrl-commons-1.2.1-03_27_2017_19_48_12.noarch
# rpm -q etcd
etcd-3.1.0-2.el7.x86_64
# cat /etc/centos-release
CentOS Linux release 7.3.1611 (Core)
```

## How to reproduce

It's possible to come up with more broken use cases, I selected two very simple ones to demonstrate the problem.

### Scenario 1

1. Login as admin and get token_one
2. Login as admin and get token_two
3. Do ping with token_one
4. Do ping with token_two
5. Log out with token_one
6. Log out with token_two

Actual Results: log out operation fails for 2nd session

```
DEBUG ping de1d160f463cd6e44e02e283a737158e7dc6dbfcc8eec4c104d214f6a48f03cf
{"status":"Ok"}
DEBUG ping 6e33dd5163faa0600604a6d2de0ada69f7fd4c30a6a8df205c56410174293661
{"status":"Ok"}
DEBUG logout de1d160f463cd6e44e02e283a737158e7dc6dbfcc8eec4c104d214f6a48f03cf
{}
DEBUG logout 6e33dd5163faa0600604a6d2de0ada69f7fd4c30a6a8df205c56410174293661
<h1>Internal Server Error</h1>
```

Expected Results: log out operation works for both sessions.

### Scenario 2

1. Login as admin and get token_one
2. Login as admin and get token_two
3. Do ping with token_one
4. Do ping with token_two
5. Log out with token_one
6. Do ping with token_one
7. Do ping with token_two

Actual Results: session using token_one is still able to use API, while session using token_two were logged out even though we successfully (sic) performed logout operation for token_one only

```
DEBUG ping 3e79d550c5218b865d053266f3db6e4da4e540b630f56db7ae03c42f5bba5b2e
{"status":"Ok"}
DEBUG ping d228b17179397b7dea2411a241a67fd8770d1a28530b346235f867ae5f1b24a5
{"status":"Ok"}
DEBUG logout 3e79d550c5218b865d053266f3db6e4da4e540b630f56db7ae03c42f5bba5b2e
{}
DEBUG ping 3e79d550c5218b865d053266f3db6e4da4e540b630f56db7ae03c42f5bba5b2e
{"status":"Ok"}
DEBUG ping d228b17179397b7dea2411a241a67fd8770d1a28530b346235f867ae5f1b24a5
{"errors":{"message":"Unauthorized"}}
```

Expected Results: after logging out session with token_one, this session can no longer perform any operations without affecting any other sessions.

## Addtitional Details

When Tendrl user is logged in, Tendrl API generates bearer token for him/her and stores it into etcd  like this:

```
# etcdctl --endpoints http://${HOSTNAME}:2379 get /_tendrl/users/admin/access_token
200bb89c7e77e822521017dfb5a95efda149044a66b92ca1f3183234d28d3c81
```

Then the user can use this token to use Tendrl API.

When user logs out, the token is deleted from the etcd:

```
# etcdctl --endpoints http://${HOSTNAME}:2379 get /_tendrl/users/admin/access_token
Error:  100: Key not found (/_tendrl/users/admin/access_token) [8905500]
```

This approach is broken by design and it only works with a single user session. 

When user opens multiple sessions, because the ` /_tendrl/users/admin/access_token` key in etcd is just overwritten, so that this value stores the last open session only, no matter how many open sessions we have. On the other hand, the Tendrl API server still caches tokens somehow, so that multiple user sessions seems to be working at first, until some session doesn't logout or until the API server isn't restarted.

**Comment by mbukatov** [comment]
For reference, there are my reproducer script, which assumes that:

* `USM_SERVER` variable contains correct full url for Tendrl API
* admin user password is `admin123` :-)
* tendrl api server is up and running

```
#!/bin/bash
USM_SERVER=http://mbukatov-usm1-server.qe.tendrl.org:9292/1.0/

tendrl_login()
{
  curl -H 'Content-Type: application/json' -X POST -d '{"username": "admin", "password":"admin123"}' "${USM_SERVER}/login" 2>/dev/null | jq '.access_token' | sed 's/"//g'
}

tendrl_ping()
{
  bearer_token=$1
  echo DEBUG ping ${bearer_token}
  curl -H 'Content-Type: application/json' -H "Authorization: Bearer ${bearer_token}" "${USM_SERVER}/ping"
  echo
}

tendrl_logout()
{
  bearer_token=$1
  echo DEBUG logout ${bearer_token}
  curl -H 'Content-Type: application/json' -X DELETE -H "Authorization: Bearer ${bearer_token}" "${USM_SERVER}/logout"
  echo
}

# case one

TOKEN_ONE=$(tendrl_login)
TOKEN_TWO=$(tendrl_login)

tendrl_ping ${TOKEN_ONE}
tendrl_ping ${TOKEN_TWO}

tendrl_logout ${TOKEN_ONE}
tendrl_logout ${TOKEN_TWO}

# case two

TOKEN_ONE=$(tendrl_login)
TOKEN_TWO=$(tendrl_login)

tendrl_ping ${TOKEN_ONE}
tendrl_ping ${TOKEN_TWO}

tendrl_logout ${TOKEN_ONE}

tendrl_ping ${TOKEN_ONE}
tendrl_ping ${TOKEN_TWO}
```

**Comment by anivargi** [comment]
@mkudlej there is a logout related fix on master.

**Comment by mbukatov** [comment]
Scenario 1 in this report has been automated as [test_login_multiple_sessions](https://github.com/Tendrl/usmqe-tests/blob/da4816675129e8add97c69b7fcd0a722b39b05bd/usmqe_tests/api/tendrl/others/test_authentication.py#L51), scenario 2 as [test_login_multiple_sessions_twisted](https://github.com/Tendrl/usmqe-tests/blob/da4816675129e8add97c69b7fcd0a722b39b05bd/usmqe_tests/api/tendrl/others/test_authentication.py#L65) - we will recheck results of both test cases with new packages.

**Comment by mbukatov** [comment]
Based on test run with tendrl-api-1.2.3-04_19_2017_14_16_32.noarch:

```
usmqe_tests/api/others/test_authentication.py::test_login_multiple_sessions XPASS
usmqe_tests/api/others/test_authentication.py::test_login_multiple_sessions_twisted XPASS
```

I'm closing this issue.
