### ISSUE TITLE
[security] Tendrl API stores bearer token [sic] in etcd in plain text

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#119]
Tendrl API documentation seems to suggest that *bearer token* is used during auth. process, see:

> The access token can be used as a Bearer token in subsequent requests to recognize the current user.

source: [docs/authentication.adoc](https://github.com/Tendrl/api/blob/c9c99e8/docs/authentication.adoc)

That said, the token is just stored in plain text on the server side, and I'm not sure if that is a expected implementation choice for something referred to as *bearer token*, because this term is defined in OAuth 2.0 standard (see References section below) and for this reason, comes with lot of OAuth 2.0 assumptions.

For example, I would not assume that this token is stored in plain text on the server side so that I can reuse it as it is as long as I have access to etcd (replay attack). Another expectation which seems to be broken here is that bearer tokens are short lived. And the list could go on.

In other words, I don't think it's a good idea to reuse existing terminology from other well known  standards, including format of HTTP header and then implement it in our own different way from scratch.

I guess that we should either not refer to this approach as *bearer token* and be more clear about the way Tendrl authentication work or implement this properly. Right now, the documentation could be very misleading for the user compared to actual implementation.

## References

Term *bearer token* is defined in [RFC 6750](https://tools.ietf.org/html/rfc6750) which is part of OAuth 2.0 framework as follows:

>    Bearer Token
      A security token with the property that any party in possession of
      the token (a "bearer") can use the token in any way that any other
      party in possession of it can.  Using a bearer token does not
      require a bearer to prove possession of cryptographic key material
      (proof-of-possession).

Which seems to hold for Tendrl token at first sight, but this is part of OAuth and the expectations here are more specific.

**Comment by mbukatov** [comment]
@mkudlej what do you think about this?

**Comment by mkudlej** [comment]
I agree it should be clear if API implements OAuth 2.0 or not.

**Comment by mbukatov** [comment]
See few examples how these terms are used and understood:

## Why is 'Bearer' required before the token in 'Authorization' header in a HTTP request?

> Sites that use the
>
> Authorization : Bearer cn389ncoiwuencr
>
> format are most likely implementing OAuth 2.0 bearer tokens.The OAuth 2.0 Authorization Framework sets a number of other requirements to keep authorization secure, for instance requiring the use of HTTPS/TLS.

Source: https://security.stackexchange.com/questions/108662/why-is-bearer-required-before-the-token-in-authorization-header-in-a-http-re

## Google search for 'bearer token'

All results on the first page are all related to OAuth 2.0

**Comment by mbukatov** [comment]
@sidhax this seems like security related issue, it requires at least a good description of auth. implementation in documentation
