### ISSUE TITLE
Data not present in API as per the UI needs

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/api#123]
Below are the Keys where UI is expecting an Array/List instead of a string.

GetNodeList API
- tags
         Currently: "tags": "[\"ceph/osd\", \"tendrl/node\"]"
         Expected: "tags": ["ceph/osd", "tendrl/node"]\"
- disks
         * All the devices are listed under disks as an object. We can have devices key(Example) inside disks which will be an array of devices
        Currently:      
```
 "disks": {
        "free": {
                 "ep5n.fxp0d3bezae": ""
        },
        "tyyg.se1widpsiic": {
                "device_name": "/dev/vda1",
                 "disk_id": "tyyG.SE1wIdpsiiC"
        },
        "k8dl.se1widpsiic": {
                 "device_name": "/dev/vda1",
                 "disk_id": "tyyG.SE1wIdpsiiC"
        },
        "ep5n.fxp0d3bezae": {
                 "device_name": "/dev/vda1",
                 "disk_id": "tyyG.SE1wIdpsiiC"
        },
        "used": {
                 "pbxm.se1widpsiic": "",
                 "tyyg.se1widpsiic": "",
                  "k8dl.se1widpsiic": "",
                  "yphi.se1widpsiic": ""
        }
```
         Expected:
```
 "disks": {
        "free": {
          "ep5n.fxp0d3bezae": ""
        },
        devices:[{
                  "device_name": "/dev/vda1",
                 "disk_id": "pbxm.se1widpsiic"
                    }, {
                 "device_name": "/dev/vda1",
                 "disk_id": "tyyG.SE1wIdpsiiC"
                   },{
                 "device_name": "/dev/vda1",
                 "disk_id": "ep5n.fxp0d3bezae"
        }],
        "used": {
          "pbxm.se1widpsiic": "",
          "tyyg.se1widpsiic": "",
        }
}
```
- networks.ipv4
         Currently: "ipv4": ["10.70.43.194"]
         Expected: "ipv4": ["10.70.43.194"]

- networks
     * Can we have multiple networks associated with a host? if yes then the "networks" key should be an array.

- messages
Currently, the Node list is huge(2 MB) and as we are frequently calling this API on UI, so it will reduce the performance of the UI and I can see the messages key inside the node list, which is huge. So ideally, messages key should not be the part of GetNodeList.

@anivargi @r0h4n @brainfunked @nthomas-redhat @sankarshanmukhopadhyay

**Comment by r0h4n** [comment]
The tendrl backend stores lists as json array, either the API or the UI has to decode the json array

**Comment by anivargi** [comment]
@cloudbehl I am looking into this.

**Comment by sankarshanmukhopadhyay** [comment]
@anivargi it would seem it is from the GetNodeList - 

> Currently, the Node list is huge(2 MB) and as we are frequently calling this API on UI, so it will reduce the performance of the UI and I can see the messages key inside the node list, which is huge. So ideally, messages key should not be the part of GetNodeList.

**Comment by gnehapk** [comment]
@anivargi Yes, its from GetNodeList API.
