### ISSUE TITLE
After installed without errors the browser display a message "Server not Found!"

### ISSUE THREAD

**Issue by pmjunior** [Tendrl/api#125]
I used the the documentation available at link: https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference and after done I receive the message "Server not Found!" at browser.

I’m forwarding the image of error as an attachment.
![screenshot from 2017-03-31 09-12-52](https://cloud.githubusercontent.com/assets/10977730/24550439/6a0558d6-15f4-11e7-841a-934524f5d947.png)

**Comment by pmjunior** [comment]
Verifiyng the logs from tendrl-api, I realized that are receiving a HTTP 401 message as below:

● tendrl-apid.service - Tendrl Api Daemon
   Loaded: loaded (/usr/lib/systemd/system/tendrl-apid.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-30 19:59:39 UTC; 8min ago
 Main PID: 20816 (puma)
   CGroup: /system.slice/tendrl-apid.service
           └─20816 puma 3.6.0 (tcp://0.0.0.0:9292) [tendrl-api]

Mar 30 19:59:39 ceph-admin-tst puma[20816]: Use Ctrl-C to stop
Mar 30 20:00:41 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:41 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0168
Mar 30 20:00:41 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:41 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0127
Mar 30 20:00:42 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:42 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0067
Mar 30 20:00:42 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:42 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0066
Mar 30 20:00:43 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:43 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0342
Mar 30 20:00:43 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:43 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0112
Mar 30 20:00:46 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:46 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0067
Mar 30 20:00:46 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:00:46 +0000] "GET //1.0/GetClusterList HTTP/1.1" 401 37 0.0065
Mar 30 20:04:15 ceph-admin-tst puma[20816]: 200.143.192.70 - - [30/Mar/2017:20:04:15 +0000] "POST //1.0/login HTTP/1.1" 401 56 0.1309
[root@ceph-admin-tst tendrl]#

**Comment by r0h4n** [comment]
Hi @pmjunior , please provide some more details
- Did you also finish "Storage Node Installation" (https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference)
- What platform are you running Tendrl on (fedora, rhel, centos?)

**Comment by pmjunior** [comment]
Hi @r0h4n, yes, I finished "Storage Node Installation" below I post the status of some services:

[root@ceph-admin-tst ~]# systemctl status etcd
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-30 18:47:24 UTC; 18h ago
 Main PID: 18084 (etcd)
   CGroup: /system.slice/etcd.service
           └─18084 /usr/bin/etcd --name=default --data-dir=/var/lib/etcd/default.etcd --listen-client-urls=http://200.130.75.95:2379

Mar 31 12:38:49 ceph-admin-tst etcd[18084]: compacted raft log at 4395532
Mar 31 12:38:55 ceph-admin-tst etcd[18084]: purged file /var/lib/etcd/default.etcd/member/snap/000000000000000c-000000000042623e.snap successfully
Mar 31 12:42:47 ceph-admin-tst etcd[18084]: start to snapshot (applied: 4410533, lastsnap: 4400532)
Mar 31 12:42:47 ceph-admin-tst etcd[18084]: saved snapshot at index 4410533
Mar 31 12:42:47 ceph-admin-tst etcd[18084]: compacted raft log at 4405533
Mar 31 12:42:55 ceph-admin-tst etcd[18084]: purged file /var/lib/etcd/default.etcd/member/snap/000000000000000c-000000000042894f.snap successfully
Mar 31 12:46:39 ceph-admin-tst etcd[18084]: start to snapshot (applied: 4420534, lastsnap: 4410533)
Mar 31 12:46:39 ceph-admin-tst etcd[18084]: saved snapshot at index 4420534
Mar 31 12:46:39 ceph-admin-tst etcd[18084]: compacted raft log at 4415534
Mar 31 12:46:55 ceph-admin-tst etcd[18084]: purged file /var/lib/etcd/default.etcd/member/snap/000000000000000c-000000000042b060.snap successfully
[root@ceph-admin-tst ~]# 

[root@ceph-admin-tst ~]# systemctl status carbon-cache
● carbon-cache.service - Graphite Carbon Cache
   Loaded: loaded (/usr/lib/systemd/system/carbon-cache.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-30 18:43:55 UTC; 18h ago
 Main PID: 16827 (carbon-cache)
   CGroup: /system.slice/carbon-cache.service
           └─16827 /usr/bin/python2 -s /usr/bin/carbon-cache --config=/etc/carbon/carbon.conf --pidfile=/var/run/carbon-cache.pid --logdir=/var/log/c...

Mar 30 18:43:55 ceph-admin-tst systemd[1]: Starting Graphite Carbon Cache...
Mar 30 18:43:55 ceph-admin-tst systemd[1]: PID file /var/run/carbon-cache.pid not readable (yet?) after start.
Mar 30 18:43:55 ceph-admin-tst systemd[1]: Started Graphite Carbon Cache.
[root@ceph-admin-tst ~]#

**Comment by pmjunior** [comment]
@r0h4n, I1m using CentOS 7.3 (CentOS Linux release 7.3.1611 (Core)) on the Ceph Storage using 5 (five) hosts where have 1 Admin node and 4 OSD nodes.

**Comment by r0h4n** [comment]
- Is the tendrl-node-agent service configured and running on all nodes (admin + storage).
- If above is true, you should see these nodes at on your  etcd_ip:2379/v2/keys/nodes/$node_id

Can you confirm above?

**Comment by pmjunior** [comment]
Yes, the tendrl-node-agent is running on the OSD nodes.

Follow the answer of browser with this question about etcd:

{"action":"get","node":{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406","dir":true,"nodes":[{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Networks","dir":true,"modifiedIndex":2321,"createdIndex":2321},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Os","dir":true,"modifiedIndex":298,"createdIndex":298},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Service","dir":true,"modifiedIndex":162,"createdIndex":162},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Disks","dir":true,"modifiedIndex":3079514,"createdIndex":3079514},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Memory","dir":true,"modifiedIndex":336,"createdIndex":336},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/NodeContext","dir":true,"modifiedIndex":91,"createdIndex":91},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Platform","dir":true,"modifiedIndex":131,"createdIndex":131},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/TendrlContext","dir":true,"modifiedIndex":96,"createdIndex":96},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/Cpu","dir":true,"modifiedIndex":325,"createdIndex":325},{"key":"/nodes/eb435e12-2088-4cfa-a45f-6cca9433d406/DetectedCluster","dir":true,"modifiedIndex":134,"createdIndex":134}],"modifiedIndex":91,"createdIndex":91}}

**Comment by r0h4n** [comment]
Thanks, seems like a valid issue, I have assigned it

**Comment by pmjunior** [comment]
Thank you @r0h4n, I'll appreciate your help.
