### ISSUE TITLE
Require different post request parameters as per the UI selections/options

### ISSUE THREAD

**Issue by cloudbehl** [Tendrl/api#126]
I have only this post request(mentioned below), so wanted to ask the other possible scenarios and other possible parameters that UI needs to send.

1). Which parameters will change when 'journal_colocation' is true?
2). Which exact parameters UI needs to send? (Like sds_name, sds_version, fsid etc). I think these parameters will be added to the API. So what are the parameters that API will add and what are the parameters that UI will add to this post request?
3). When the role is OSD there is parameter name as "Storage_disks" and inside disks I can see two parameters named as device and journal("device": "/dev/vdb", "journal": "/dev/vdc"). How UI is supposed to handle these parameters.
4) What are the "conf_overrides" and its parameters? As Pool creation mechanism is not been implemented in Create cluster workflow. so from where we will get these parameters?
5) "node_identifier" what are the other possible values for this parameter and from where we have to select this value?
6) Inside "sds_parameters" I can see public_network and cluster_network as parameters on a global level but in UI we are selecting these parameters for every node. So on which basis these parameters are decided?(https://redhat.invisionapp.com/share/2K8M4PQYZ#/screens/188984130)
7) what is "provisioning_ip" parameter and how UI is going to decide its value?

Need description for all these parameters after looking at the UX design. https://redhat.invisionapp.com/share/2K8M4PQYZ#/screens/205496801

API Post data for create ceph cluster.

```
{
	"sds_name": "ceph",
	"sds_version": "10.2.5",
	"sds_parameters": {
		"name": "MyCluster",
		"fsid": "140cd3d5-58e4-4935-a954-d946ceff371d",
		"public_network": "10.70.40.0/22",
		"cluster_network": "10.70.40.0/22",
		"conf_overrides": {
			"global": {
				"osd_pool_default_pg_num": 128,
				"pool_default_pgp_num": 1
			}
		}
	},
	"node_identifier": "ip",
	"node_configuration": {
		"10.70.43.102": {
			"role": "ceph/mon",
			"provisioning_ip": "10.70.43.102",
			"monitor_interface": "eth0"
		},
		"10.70.42.2": {
			"role": "ceph/mon",
			"provisioning_ip": "10.70.42.2",
			"monitor_interface": "eth0"
		},
		"10.70.42.73": {
			"role": "ceph/mon",
			"provisioning_ip": "10.70.42.73",
			"monitor_interface": "eth0"
		},
		"10.70.43.194": {
			"role": "ceph/osd",
			"provisioning_ip": "10.70.43.194",
			"journal_size": 5192,
			"journal_colocation": "false",
			"storage_disks": [{
				"device": "/dev/vdb",
				"journal": "/dev/vdc"
			}]
		},
		"10.70.42.238": {
			"role": "ceph/osd",
			"provisioning_ip": "10.70.42.238",
			"journal_size": 5192,
			"journal_colocation": "false",
			"storage_disks": [{
				"device": "/dev/vdb",
				"journal": "/dev/vdc"
			}]
		}
	}
}
```

**Comment by cloudbehl** [comment]
@anivargi @r0h4n @brainfunked @sankarshanmukhopadhyay please have a look.

**Comment by shtripat** [comment]
>> 1). Which parameters will change when 'journal_colocation' is true?

If `journal_colocation` is set as true, the value of `storage_disks` should be a list of devices and not a list of dicts. An example could be like 

```
"storage_disks": ['/dev/vdb', '/dev/vdc', '/dev/vdd']
```

Here we dont need journal mapped disk name so simple list of disks and journal would be located on the same disk. In above example there would 3 OSDs created with their journal partitions on the same disk.

>> 3). When the role is OSD there is parameter name as "Storage_disks" and inside disks I can see two >> parameters named as device and journal("device": "/dev/vdb", "journal": "/dev/vdc"). How UI is
>> supposed to handle these parameters.

In case of journal colocation UI need to send list of disks only as value of `storage_disks` but if journal colocation is set as false, the value should be a dict depicting the mapping of device to its journal disk (say for /dev/vdb the journal should exist on /dev/vdc). In UI while selecting the disks the dedicated journal mode is equivalent to `journal_colocation-false`

>> 4) What are the "conf_overrides" and its parameters? As Pool creation mechanism is not been
>> implemented in Create cluster workflow. so from where we will get these parameters?

Ideally this is anything which should be overwritten in confi file of ceph cluster. At the moment may be you can stick with only values shown in samples. @brainfunked comments?

>> 6) Inside "sds_parameters" I can see public_network and cluster_network as parameters on a global >> level but in UI we are selecting these parameters for every node. So on which basis these parameters >> are decided?(https://redhat.invisionapp.com/share/2K8M4PQYZ#/screens/188984130)

The fields `public_network` and `cluster_network` are meant to be cluster level. All the nodes selected for cluster creation should be in same subnet.

>> 7) what is "provisioning_ip" parameter and how UI is going to decide its value?

`provisioning_ip` is the IP of the node selected for cluster creation. This data should be available as part of node inventory under network details.

**Comment by cloudbehl** [comment]
@shtripat thanks for taking out the time to explain. Really Appreciated.

Just on few questions, I need more clarity.

> In case of journal colocation UI need to send list of disks only as value of storage_disks but if journal colocation is set as false, the value should be a dict depicting the mapping of device to its journal disk (say for /dev/vdb the journal should exist on /dev/vdc). In UI while selecting the disks the dedicated journal mode is equivalent to journal_colocation-false

* You said **for /dev/vdb the journal should exist on /dev/vdc**. On which basis journal disks will be decided because I don't see a Ux component mapped to this property. So will it to be decided by the API or the UI?

* Inside every node there is a Network field and that has a list of ip addresses inside ipv4 key. If the ip's are more than one how will post data look like? Will all the ip listed in ipv4 for a node have a same configuration inside the post data network_configration field?

```
      "networks": {
        "eth0": {
          "device_link": "/devices/pci0000",
          "ipv4": "[\"10.70.43.102\"]",
          "model": "Ethernet network interface",
          "netmask": "[\"255.255.252.0\"]",
          "interface_id": "usDW.ndpeucax6V1",
          "link_detected": "yes",
          "subnet": "10.70.40.0/22",
          "drive": "",
          "driver": "virtio_net",
          "hw_address": "00",
          "interface_type": "network interface",
          "ipv6": "[\"2620:52:0:4628:21a:4aff:fef7:2337\", \"fe80::21a:4aff:fef7:2337%eth0\"]",
          "sysfs_id": "/class/net/eth0",
          "driver_modules": "virtio_net",
          "interface": "eth0",
          "status": "up"
        }
      }

```

**Comment by shtripat** [comment]
>> You said for /dev/vdb the journal should exist on /dev/vdc. On which basis journal disks will be decided >> because I don't see a Ux component mapped to this property. So will it to be decided by the API or the >> UI?

I remember in UX design there is a way to say that so and so disk is used as dedicated journal and how many journals can exist on that disk. Once dedicated journals decided on a disk, we can mention which disk's journal would reside on the journal disk. If any confusion check once with Ju as well and using this screen only the dict list of `storage_disks` should be formed

>> Inside every node there is a Network field and that has a list of ip addresses inside ipv4 key. If the ip's >> are more than one how will post data look like? Will all the ip listed in ipv4 for a node have a same
>> configuration inside the post data network_configration field?

In case of multiple IPv4 addresses, I feel user the IP in `public_network` subnet should be selected and sent. @Tendrl/tendrl-core comments?
