### ISSUE TITLE
Message List for specific job is giving Internal Server Error(500)

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#127]
Making the following call to get the messages for a job is giving Internal Server Error(500) on 10.70.43.205 setup.
  
API call - 10.70.41.250:9292/1.0/jobs/c7b98511-4758-4d9e-9ff4-e9e1bc4ee059/messages/

(The Job id can be wrong as the setup(10.70.43.205) is down for now)

@anivargi @brainfunked @nthomas-redhat Please check.

**Comment by anivargi** [comment]
Same as https://github.com/Tendrl/api/issues/128

**Comment by ltrilety** [comment]
As of now when I start to import a cluster there's no `500 Internal Server Error` anymore, however there is still an issue. First the request returns `400 Bad Request`, later `404 Not Found` and few seconds before the job finishes it return `200 OK` with some response.

Checked version:
tendrl-api-1.2.3-04_26_2017_01_51_04.noarch
