### ISSUE TITLE
jobs/job_id/messages returns 500 Internal Server Error for failed jobs

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#128]
I receive `500 Internal Server Error` when I want to check out `messages_url` that is listed among attributes of the job accessible through api on `hostname/api/1.0/jobs`. Call `hostname/api/1.0/jobs/job_id/messages` with id of finished job returns valid response.
Tested with:
tendrl-api-1.2.1-04_03_2017_01_51_03.noarch

**Comment by ltrilety** [comment]
As of now when I start to import a cluster there's no `500 Internal Server Error` anymore, however there is still an issue. First the request returns `400 Bad Request`, later `404 Not Found` and few seconds before the job finishes it return `200 OK` with some response.

Checked version:
tendrl-api-httpd-1.2.3-04_26_2017_01_51_04.noarch

**Comment by fbalak** [comment]
Works as expected. --> closing
Tested with:
tendrl-api-1.2.3-04_28_2017_01_51_05.noarch
tendrl-node-agent-1.2.3-04_28_2017_00_01_03.noarch
