### ISSUE TITLE
cluster_id/Flows api call returns 500 Internal Server Error

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#129]
I receive `500 Internal Server Error` when I call GET `hostname/api/1.0/cluster_id/Flows` where `cluster_id` represents `integration_id` of an imported gluster cluster.
Tested with:
tendrl-api-1.2.1-04_03_2017_01_51_03.noarch

**Comment by mbukatov** [comment]
@fbalak could you recheck if this is still relevant?
