### ISSUE TITLE
missing node in imported cluster

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#134]
Sometimes import of gluster trusted pool fails to add all nodes in the cluster node list.

Scenario in my case:
1. Install all machines. Cluster was detected on tendrl site and all nodes has the same cluster `detectedcluster` fields.
2. Import cluster using `ImportCluster` API call with following data:
    ```
    {"node_ids": ["6fb025b9-0e79-4cdb-8a00-f94a449f7e01", "efd31949-8758-4e51-a1c3-aecca75b1f7d", "ee1b4100-3a4f-4c8d-94c5-463edbfd5723", "99811961-0cf7-439c-b5c6-7f609967012f"], "sds_type":"gluster"}
    ```
    BTW I checked ids of machines against ids in etcd nodes and they matched.
3. Run the `ImportCluster` API call again. Not sure if that the reason though and not sure if the first job was finished when the second was created. Anyway the first jobs finishes and the second one fails as expected.
    ```
    [
      {
    "job_id": "251cd088-e491-4bb4-b7d3-30a4a886a93a",
    "status": "failed",
    "flow": "ImportCluster",
    "parameters": {
    "node_ids": [
      "6fb025b9-0e79-4cdb-8a00-f94a449f7e01",
      "efd31949-8758-4e51-a1c3-aecca75b1f7d",
      "ee1b4100-3a4f-4c8d-94c5-463edbfd5723",
      "99811961-0cf7-439c-b5c6-7f609967012f"
    ],
    "sds_type": "gluster",
    "DetectedCluster.sds_pkg_name": "gluster",
    "Node[]": [
      "6fb025b9-0e79-4cdb-8a00-f94a449f7e01",
      "efd31949-8758-4e51-a1c3-aecca75b1f7d",
      "ee1b4100-3a4f-4c8d-94c5-463edbfd5723",
      "99811961-0cf7-439c-b5c6-7f609967012f"
    ],
    "TendrlContext.integration_id": "4025d26e-59e9-4233-b3b3-7f7c15e930fc"
    },
    "created_at": "2017-04-05T08:26:17Z",
    "status_url": "/jobs/251cd088-e491-4bb4-b7d3-30a4a886a93a/status",
    "messages_url": "/jobs/251cd088-e491-4bb4-b7d3-30a4a886a93a/messages"
    },
      {
    "job_id": "8d9c3143-4a08-4e5d-95ea-d2c7fa1badef",
    "status": "finished",
    "flow": "ImportCluster",
    "parameters": {
    "node_ids": [
      "6fb025b9-0e79-4cdb-8a00-f94a449f7e01",
      "efd31949-8758-4e51-a1c3-aecca75b1f7d",
      "ee1b4100-3a4f-4c8d-94c5-463edbfd5723",
      "99811961-0cf7-439c-b5c6-7f609967012f"
    ],
    "sds_type": "gluster",
    "DetectedCluster.sds_pkg_name": "gluster",
    "Node[]": [
      "6fb025b9-0e79-4cdb-8a00-f94a449f7e01",
      "efd31949-8758-4e51-a1c3-aecca75b1f7d",
      "ee1b4100-3a4f-4c8d-94c5-463edbfd5723",
      "99811961-0cf7-439c-b5c6-7f609967012f"
    ],
    "TendrlContext.integration_id": "cec42018-46c4-4d0f-9f3d-be64212aa277"
    },
    "created_at": "2017-04-05T08:25:52Z",
    "status_url": "/jobs/8d9c3143-4a08-4e5d-95ea-d2c7fa1badef/status",
    "messages_url": "/jobs/8d9c3143-4a08-4e5d-95ea-d2c7fa1badef/messages"
    }
    ],
    ```
4. A new cluster is present in tendrl, however a node with id `99811961-0cf7-439c-b5c6-7f609967012f` is missing in it. And so clusters section in `GetNodeList` is not empty and another cluster can be successfully imported even when it's the same trusted pool as the one already imported.

Used packages:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch

**Comment by shtripat** [comment]
I am trying to  simulate this in my setup. Will update soon

**Comment by shtripat** [comment]
@ltrilety I tried import flow with a 4 node gluster cluster and it works properly as expected.
I can see all the 4 nodes listed under `/clusters/{id}/nodes` and under `/nodes/{id}/TendrlContext` value is populated properly for all the nodes.

Also I tried to import the cluster with same set of nodes and it fails as expected with error `Nodes already participate in existing cluster`.

May be you should check the node-agent logs on the non-listed node and see if some error while syncing the cluster context after import flow.

**Comment by ltrilety** [comment]
@shtripat sorry about that, I didn't expect to be easily reproduced. It happens only scarcely to me and moreover a slow network could be in the play too as it happens when I was importing a cluster over VPN.

I'll try to provide more information if it happens again. I already re-install my machines.

**Comment by nthomas-redhat** [comment]
@ltrilety any update on this?

**Comment by ltrilety** [comment]
@nthomas-redhat nope, I'll try the scenario and if it doesn't happen again I could close this issue for now. And let it be closed until it happen again. Lets hope I will have more information then.

**Comment by ltrilety** [comment]
I tried the scenario. Well, the second import doesn't fail as before actually it succeeded and so I ended with two clusters. One has 1 node the other one has 3 nodes. That's another output than before, but even so I think the issue is valid.

Checked on:
tendrl-api-doc-1.2.2-04_10_2017_01_51_03.noarch
tendrl-commons-1.2.2-04_10_2017_04_42_05.noarch
tendrl-dashboard-1.2.1-04_10_2017_04_11_04.noarch
tendrl-performance-monitoring-1.2.2-04_10_2017_03_02_03.noarch
tendrl-api-1.2.2-04_10_2017_01_51_03.noarch
tendrl-api-httpd-1.2.2-04_10_2017_01_51_03.noarch
tendrl-node-agent-1.2.2-04_10_2017_00_01_03.noarch
etcd-3.1.0-2.el7.x86_64

**Comment by ltrilety** [comment]
It could happen if the `import_cluster` is called from UI too.

![bad_cluster](https://cloud.githubusercontent.com/assets/22369834/25714441/4cac1698-30f8-11e7-882e-b163135a61b3.png)

Checked with:
tendrl-api-httpd-1.2.3-05_04_2017_01_51_04.noarch
tendrl-dashboard-1.2.3-05_04_2017_04_11_06.noarch
tendrl-performance-monitoring-1.2.3-05_04_2017_11_57_30.noarch
tendrl-api-doc-1.2.3-05_04_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-05_04_2017_11_40_12.noarch
etcd-3.1.3-1.el7.x86_64
tendrl-api-1.2.3-05_04_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_04_2017_05_13_04.noarch

**Comment by r0h4n** [comment]
Hey, can you reproduce this one and more job payload and job msgs and node-agent logs

**Comment by ltrilety** [comment]
still valid on:
tendrl-commons-1.2.3-05_18_2017_05_13_05.noarch
tendrl-dashboard-1.2.3-05_18_2017_04_11_06.noarch
tendrl-performance-monitoring-1.2.3-05_18_2017_03_02_04.noarch
tendrl-api-1.2.3-05_18_2017_10_45_13.noarch
tendrl-api-httpd-1.2.3-05_18_2017_10_45_13.noarch
tendrl-node-agent-1.2.3-05_18_2017_04_16_25.noarch
tendrl-api-doc-1.2.3-05_18_2017_10_45_13.noarch

Look for number of hosts on the picture (there was just one gluster trusted pool with 4 hosts on my settings):
![image](https://cloud.githubusercontent.com/assets/22369834/26190259/d123b498-3ba8-11e7-971c-bcb7ea7823da.png)

**Comment by anivargi** [comment]
@r0h4n

**Comment by r0h4n** [comment]
@ltrilety Is this still valid? Havent seen this in new builds

**Comment by ltrilety** [comment]
@r0h4n I am not sure about the newest build but it was valid for yesterday build:
tendrl-commons-1.3.0-05_22_2017_05_13_04.noarch
tendrl-dashboard-1.3.0-05_22_2017_04_11_04.noarch
tendrl-performance-monitoring-1.3.0-05_22_2017_03_02_07.noarch
tendrl-api-1.3.0-05_22_2017_01_51_04.noarch
tendrl-api-httpd-1.3.0-05_22_2017_01_51_04.noarch
tendrl-node-agent-1.3.0-05_22_2017_00_01_06.noarch
tendrl-api-doc-1.3.0-05_22_2017_01_51_04.noarch
