### ISSUE TITLE
API docs example missing key information

### ISSUE THREAD

**Issue by julienlim** [Tendrl/api#141]
@Tendrl/tendrl_documentation 

In trying to query for the jobs listing or job details per https://github.com/Tendrl/api/blob/master/docs/jobs.adoc, the examples are missing key information for the sample requests to work.  Specifically, if you follow the examples provided, you get an unauthorization message.

In order to correctly query using the API, user needs to pass a token, and it's not documented how to properly do so.

After hacking away at it, here's the correct sample request that worked for me:

**List jobs:**

   curl -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>' http://<ip_address>/api/1.0/jobs

e.g.
   curl -H 'Content-Type: application/json' -H 'Authorization: Bearer 1ca0ceb1779dcd7c2710e80ff00cacfda9f065c3c0649b0fdb381c5b7cb1792f' http://127.0.0.1/api/1.0/jobs

Note:

**Query details for a single job:**

   curl -H 'Content-Type: application/json' -H 'Authorization: Bearer <token>' http://<ip_address>//api/1.0/jobs/<job_id>

e.g.
   curl -H 'Content-Type: application/json' -H 'Authorization: Bearer 1ca0ceb1779dcd7c2710e80ff00cacfda9f065c3c0649b0fdb381c5b7cb1792f' http://127.0.0.1//api/1.0/jobs/31b06f59-f673-483a-9939-ec781e534af4

**Comment by anivargi** [comment]
The docs are updated.
