### ISSUE TITLE
GetNodeList bad clusters list

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#152]
Restart of storage nodes often destroy possibility to correctly import a cluster. After restart sometimes two cluster are detected where there's only one and/or the cluster id is empty.

The issue could be related to https://github.com/Tendrl/node-agent/issues/373

Example of clusters list from `GetNodeList` api call result:
```
{
"nodes": [],
"clusters": [
  {
"cluster_id": "",
"sds_name": "gluster",
"sds_version": "3.9.1",
"node_ids": [
  "a7915b56-ac90-479f-89fe-14acbd0e9d9d"
],
},
  {
"cluster_id": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
"sds_name": "gluster",
"sds_version": "3.9.1",
"node_ids": [
  "32c5d940-42b8-4633-a9b6-828a73d1ed5f",
  "42308924-b142-4596-81b9-e9d637bbacc5",
  "54f91e29-f982-4853-ac97-180aa26df553"
],
}
],
}
```

Used packages:
tendrl-api-httpd-1.2.2-04_18_2017_01_51_04.noarch
tendrl-api-doc-1.2.2-04_18_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_17_2017_20_19_16.noarch
tendrl-dashboard-1.2.1-04_18_2017_04_11_04.noarch
tendrl-performance-monitoring-1.2.2-04_18_2017_03_02_04.noarch
etcd-3.1.0-2.el7.x86_64
tendrl-api-1.2.2-04_18_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-04_18_2017_02_22_22.noarch

**Comment by anivargi** [comment]
@ltrilety is this still a issue?

**Comment by ltrilety** [comment]
@anivargi probably not, I didn't hit this issue a long time. That said I am closing this issue
