### ISSUE TITLE
Single API call for Create RBD which handles both - creation using existing and new pool as a backing pool

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#153]
Creation of RBD involves two scenarios -
1) Using existing pool or
2) Creating new pool as the backing pool

Currently, the API for creating pool and RBD is different. So in the UI, if user chooses the second option, ideally user has to wait on the create pool screen till the pool is created. 
If we can have a single API call for handling both process(creating pool and then continuing rbd creation) - i.e UI can send pool creation job id along with rbd creation details, this issue can be handled. 

@anivargi @brainfunked @nthomas-redhat @shtripat @sankarshanmukhopadhyay

**Comment by r0h4n** [comment]
@gnehapk @anivargi the backend parts are done, and the API will reflect the new optional inputs 

https://github.com/Tendrl/ceph-integration/pull/221/files#diff-c9fd4531a0ac3580d1736d30e3d25f9aR153

@gnehapk @cloudbehl Is this complete on the UI?

**Comment by gnehapk** [comment]
@r0h4n Not yet. We will take this up.
