### ISSUE TITLE
Event List is not populated for every task in the UI

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#158]
API for getting event list is giving "404" status code for some tasks in the UI.

For eg - 

Request - http://10.70.43.137/api/1.0/jobs/831655a2-6007-420f-9007-cbca0ba1449e/messages 
Response - {"errors":{"message":"Key not found"}} with status code 404. 

@brainfunked @anivargi @nthomas-redhat @sankarshanmukhopadhyay

**Comment by anivargi** [comment]
@gnehapk is this still a issue?

**Comment by gnehapk** [comment]
@anivargi The error is not coming now. But the response is returning empty list of messages.

Checked with - http://10.70.42.170/api/1.0/

URL - http://10.70.42.170/api/1.0/jobs/6f66ae89-44de-4ef8-a567-b5d7c3b5239c/messages and
URL - http://10.70.42.170/api/1.0/jobs/0621099c-3eb7-4e24-a5d5-9017ef6e749b/messages

Both APIs are returning empty array.

**Comment by anivargi** [comment]
@gnehapk I can't access those instances. Do you have any other instance where you have the same issue?
