### ISSUE TITLE
import of ceph cluster

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#165]
A ceph cluster import job remains in New state and never change to processing and so later to finished/failed.

Used packages:
tendrl-api-httpd-1.2.3-05_03_2017_01_51_04.noarch
tendrl-dashboard-1.2.3-05_03_2017_04_11_33.noarch
tendrl-performance-monitoring-1.2.3-05_03_2017_03_02_33.noarch
tendrl-api-doc-1.2.3-05_03_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-05_03_2017_00_01_04.noarch
etcd-3.1.3-1.el7.x86_64
tendrl-api-1.2.3-05_03_2017_01_51_04.noarch
tendrl-commons-1.2.3-05_03_2017_05_13_04.noarch

**Comment by ltrilety** [comment]
Logs and configurations:
[evidence-files.zip](https://github.com/Tendrl/api/files/973444/evidence-files.zip)

**Comment by shtripat** [comment]
With latest builds, the import cluster works fine. Would suggest to try once and update.

**Comment by ltrilety** [comment]
It was working on newer packages. However even when I was creating the issue I didn't thought the issue remains. It looked more like random problem. Hence I provided all logs and configurations.

That said I am closing the issue for now and if it happens again I'll reopen it.
