### ISSUE TITLE
CephUpdatePool - cannot change pool name and other attributes by one function call

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/api#168]
Not it is not possible to change pool name and other attributes by one function call.
I think that it should be possible to do so or there should be 2 functions instead of one. One for renaming pool and other one for changing pool attributes.

**Comment by shtripat** [comment]
@Tendrl/tendrl-core if you feel we can have additional flow defined for renaming a pool, it can be added.
Plz suggest...

**Comment by r0h4n** [comment]
@shtripat Yes, please go ahead
