### ISSUE TITLE
jobs API call returns "Invalid JSON received." error

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#173]
I have created 2 cluster import jobs and after it following API call starts to return:  `"errors": {"message": "Invalid JSON received."}` In dashboard it also doesn't work.

`curl -XGET -H "Authorization: Bearer 9af866653ff94d7a9a3892cc3ee2675a51e851fbae00ed10aebc3b3b126cab75" http://fbalak-usm1-server.usmqe.lab.eng.brq.redhat.com/api/1.0/jobs`

There is log from `journalctl -u tendrl-apid`:
[apid-journalctl.txt](https://github.com/Tendrl/api/files/1005090/apid-journalctl.txt)

Tested with:
tendrl-commons-1.2.3-05_16_2017_19_00_14.noarch
tendrl-node-agent-1.2.3-05_16_2017_14_54_59.noarch
tendrl-node-monitoring-1.2.3-05_16_2017_04_37_32.noarch
tendrl-api-1.2.3-05_16_2017_01_51_04.noarch

**Comment by anivargi** [comment]
@fbalak can you mail me the etcd instance details?

**Comment by fbalak** [comment]
@anivargi I have sent you a mail.

**Comment by anivargi** [comment]
@fbalak replied.

**Comment by fbalak** [comment]
Seems ok.
Tested with:
tendrl-api-1.3.0-05_23_2017_11_05_13.noarch
tendrl-node-agent-1.3.0-05_23_2017_03_13_07.noarch
