### ISSUE TITLE
presence of cluster which is currently imported in GetNodeList

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#183]
`GetNodeList` returns in clusters section the cluster which is currently imported. When the import cluster job is started such cluster should not be part of `GetNodeList` response.

Used packages:
tendrl-api-doc-1.3.0-05_23_2017_11_05_13.noarch
tendrl-performance-monitoring-1.3.0-05_23_2017_06_29_05.noarch
tendrl-api-1.3.0-05_23_2017_11_05_13.noarch
tendrl-api-httpd-1.3.0-05_23_2017_11_05_13.noarch
tendrl-node-agent-1.3.0-05_23_2017_03_13_07.noarch
tendrl-commons-1.3.0-05_23_2017_05_13_05.noarch
tendrl-dashboard-1.3.0-05_23_2017_07_55_05.noarch

**Comment by anivargi** [comment]
@r0h4n is there a flag we add to the nodes when they are selected for importing using which I can filter while the cluster is being imported?

**Comment by r0h4n** [comment]
There is no lock/flag for Nodes participating in a import or create cluster call. We will have to mark this as a known issue and fix it soon.

For now, the test case has to be such that we do not successively import/create using the same set of Nodes

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/commons/pull/538

You will not be able to import Nodes already participating in a import/create/expand api cal
