### ISSUE TITLE
jobs returns 400 Bad Request

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#184]
After submitting second import for some unknown reason jobs call starts to return `400 Bad Request`.
There's following error in tendrl-node-agent log:
2017-05-23 13:23:01.655087+00:00 - node_agent - /usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py:248 - _run - ERROR - Job processing failure, error:type - KeyError: [{u'function': u'run', u'line': 327, u'file': u'/usr/lib64/python2.7/site-packages/gevent/greenlet.py', u'statement': u'result = self._run(*self.args, **self.kwargs)'}, {u'function': u'_run', u'line': 103, u'file': u'/usr/lib/python2.7/site-packages/tendrl/commons/jobs/__init__.py', u'statement': u'if job.payload["type"] == NS.type and \\'}]

Configurations and logs:
[evidence-files.zip](https://github.com/Tendrl/api/files/1022314/evidence-files.zip)

Used packages:
tendrl-performance-monitoring-3.0-alpha.el7scon.noarch
tendrl-api-httpd-3.0-alpha.el7scon.noarch
tendrl-node-agent-3.0-alpha.2.el7scon.noarch
tendrl-dashboard-3.0-alpha.el7scon.noarch
tendrl-api-3.0-alpha.el7scon.noarch
tendrl-api-doc-3.0-alpha.el7scon.noarch
tendrl-commons-3.0-alpha.2.el7scon.noarch

**Comment by r0h4n** [comment]
When you say "after submitting second import" , do you mean you submitted a original import cluster job and then while the original import cluster job was "processing" you submitted another import cluster job with the same set of parameters?

**Comment by ltrilety** [comment]
@r0h4n I have two clusters. First one was imported successfully I start to import the second one and then it happens.

**Comment by r0h4n** [comment]
@anmolsachan Please try to reproduce this issue

Steps:
1) Have 1 ceph cluster, 1 gluster cluster ready
2) Install tendrl-node-agents, tendrl-perf-mon, tendrl-node-mon,  on all nodes of these clusters
3) Import ceph cluster via tendrl-dashboard
4) After successful import of ceph cluster, Import the gluster cluster via tendrl-dashboard

@ltrilety Please correct me if the steps are wrong

**Comment by ltrilety** [comment]
@r0h4n your reproduction steps are correct.

**Comment by anmolsachan** [comment]
@r0h4n @ltrilety  I tested for the issue. Followed the steps exactly as in above. Both the clusters got imported successfully. 
The following was the setup:

tendrl-api-1.3.0-05_29_2017_03_52_03.noarch
tendrl-node-agent-1.3.0-05_29_2017_03_13_03.noarch
tendrl-performance-monitoring-1.3.0-05_29_2017_06_29_03.noarch
tendrl-node-monitoring-1.3.0-05_29_2017_04_25_03.noarch
tendrl-dashboard-1.3.0-05_29_2017_07_55_04.noarch
tendrl-commons-1.3.0-05_29_2017_05_13_04.noarch
tendrl-api-httpd-1.3.0-05_29_2017_03_52_03.noarch
tendrl-gluster-integration-1.3.0-05_29_2017_06_23_03.noarch
tendrl-ceph-integration-1.3.0-05_29_2017_03_20_04.noarch

**Comment by r0h4n** [comment]
@ltrilety can you still reproduce this with builds mentioned?

**Comment by ltrilety** [comment]
@anmolsachan @r0h4n Please did you look to the attached configuration and logs? As I don't believe it happened every time even on the previous version.
I'll try that with newer one when possible.

**Comment by ltrilety** [comment]
As expected it works fine on new build.

Tested packages:
tendrl-node-agent-3.0-alpha.7.el7scon.noarch
tendrl-commons-3.0-alpha.7.el7scon.noarch
tendrl-performance-monitoring-3.0-alpha.4.el7scon.noarch
tendrl-api-3.0-alpha.3.el7scon.noarch
tendrl-api-httpd-3.0-alpha.3.el7scon.noarch
tendrl-dashboard-3.0-alpha.3.el7scon.noarch
tendrl-alerting-3.0-alpha.2.el7scon.noarch
tendrl-api-doc-3.0-alpha.3.el7scon.noarch
