### ISSUE TITLE
tendrl-api service listens on all interfaces by default

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#216]
Description of the problem
=====================

Service tendrl-api listens on all network interfaces by default, but the design of the Tendrl stack requires the api service to be available just on localhost: the requests from the outside are handled/routed through via actual web server (httpd).

Affected Version
=============

tendrl-api-1.4.2-1.el7.centos.noarch

Steps to reproduce
===============

1) Install Tendrl Server via tendrl-ansible.
2) Make sure tendrl-api is up and running.
3) Check network interfaces where tendrl-api service listens on.
4) Try to reach the api via `http://mbukatov-usm1-server.example.com:9292/1.0/ping` from the outside.

Actual Result
===========

Tendrl api service listens on `tcp://0.0.0.0:9292`, as can be seen in output of these commands:

```
# systemctl status tendrl-api
● tendrl-api.service - Tendrl Api Daemon
   Loaded: loaded (/usr/lib/systemd/system/tendrl-api.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-06-23 16:32:42 UTC; 13min ago
 Main PID: 838 (puma)
   CGroup: /system.slice/tendrl-api.service
           └─838 puma 3.6.0 (tcp://0.0.0.0:9292) [tendrl-api]

Jun 23 16:32:42 mbukatov-usm1-server.example.com systemd[1]: Starting Tendrl Api Daemon...
Jun 23 16:32:43 mbukatov-usm1-server.example.com puma[838]: Puma starting in single mode...
Jun 23 16:32:43 mbukatov-usm1-server.example.com puma[838]: * Version 3.6.0 (ruby 2.0.0-p648), codename: Sleepy Sunday Serenity
Jun 23 16:32:43 mbukatov-usm1-server.example.com puma[838]: * Min threads: 0, max threads: 16
Jun 23 16:32:43 mbukatov-usm1-server.example.com puma[838]: * Environment: production
Jun 23 16:32:45 mbukatov-usm1-server.example.com puma[838]: * Listening on tcp://0.0.0.0:9292
Jun 23 16:32:45 mbukatov-usm1-server.example.com puma[838]: Use Ctrl-C to stop
Jun 23 16:39:22 mbukatov-usm1-server.example.com puma[838]: 10.40.3.125 - - [23/Jun/2017:16:39:22 +0000] "POST //1.0/login HTTP/1.1"...0.1457
Jun 23 16:39:22 mbukatov-usm1-server.example.com puma[838]: 10.40.3.125 - - [23/Jun/2017:16:39:22 +0000] "GET //1.0/GetClusterList H...0.0702
Jun 23 16:39:41 mbukatov-usm1-server.example.com puma[838]: 10.40.3.125 - - [23/Jun/2017:16:39:41 +0000] "GET //1.0/GetClusterList H...0.0371
Hint: Some lines were ellipsized, use -l to show in full.
```

```
# lsof -i -P | grep ^puma
puma       838           root    7u  IPv4  17168      0t0  TCP *:9292 (LISTEN)
```

So that it's possible to talk directly to puma from the outside:

```
$ curl http://mbukatov-usm1-server.example.com:9292/1.0/ping; echo
{"status":"Ok"}
```

Expected Result
=============

Tendrl api should listen only on localhost:

```
# lsof -i -P | grep ^puma
puma       838           root    7u  IPv4  17168      0t0  TCP localhost:9292 (LISTEN)
```

and the only component which uses this localhost connection is httpd, all the other components should go through public interface provided by web server.

It's not possible to talk directly to puma from the outside:

```
$ curl http://mbukatov-usm1-server.example.com:9292/1.0/ping
curl: (7) Failed to connect to mbukatov-usm1-server.example.com port 9292: Connection refused
```

**Comment by r0h4n** [comment]
@anivargi please take a look at this one

**Comment by r0h4n** [comment]
@anivargi can you atleast provide a update here?

**Comment by anivargi** [comment]
Fixed in https://github.com/Tendrl/api/pull/272

**Comment by mbukatov** [comment]
ok
