### ISSUE TITLE
Data provided by api are not fully encoded in json format, lists are formatted in an escaped strings

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#220]
Response for `GetNodeList` call is not fully encoded in json format: sometimes data is provided as a single string value when it should be encoded just as a list of strings instead.

This means that sometimes, one needs to manually parse string values into list of strings to get sense of the data, and sometimes one can just consume the list as expected.

## Version

```
# rpm -qa 'tendrl-*'
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
tendrl-api-doc-1.4.2-1.el7.centos.noarch
```

## Reproducer

1. Install Tendrl Server using tendrl-ansible
2. Create some cluster via Tendrl (so that there are more details tracked for each storage node)
3. Run `/api/1.0/GetNodeList` call and save the result, example:

```
$ curl 'http://mbukatov-usm1-server.example.com/api/1.0/GetNodeList' -H 'Authorization: Bearer 0d893cb67d1ea6e19a34ca6d1add9436d99be33f8bc15b3f596a47c5bdaa05f6' > getnodelist.response.json
$ jq '.' getnodelist.response.json > getnodelist.response.pretty.json
```

4. Seach for lists of values in the response

## Actual Result

There are lot of exceptions where list of strings are exported as a single string values with json list syntax being escaped.

Quick grep search reveals that there are 78 instances of list items, but almost all of them - 76 - are provided as a single string value:

```
$ grep '\[' getnodelist.response.pretty.json | wc -l
78
$ grep '\[' getnodelist.response.pretty.json | grep '"\[' | wc -l
76
$ grep '\[' getnodelist.response.pretty.json | grep ' \[' | wc -l
2
$ grep '\[' getnodelist.response.pretty.json | grep ' \[' 
  "nodes": [
  "clusters": []
```

Digging deeper, let's see some example:

```
$ grep '\[' getnodelist.response.pretty.json | grep '"\[' | sed 's/^ *//g' | head
"tags": "[\"provisioner/ceph\", \"tendrl/central-store\", \"tendrl/server\", \"tendrl/node_a6662d3c-4757-45c1-b3d8-4565cb4b0a1c\", \"tendrl/monitor\", \"tendrl/node\"]",
"ipv4": "[\"10.34.108.90\"]",
"ipv6": "[\"fe80::5054:ff:fe70:318%ens3\", \"2620:52:0:226c:5054:ff:fe70:318\"]",
"netmask": "[\"255.255.255.0\"]",
"role": "[\"provisioner/ceph\", \"tendrl/central-store\", \"tendrl/server\", \"tendrl/node_a6662d3c-4757-45c1-b3d8-4565cb4b0a1c\", \"tendrl/monitor\", \"tendrl/node\"]",
"tags": "[\"tendrl/node_c692ee35-561e-4c72-a31e-22361b2040f2\", \"tendrl/node\"]",
"ipv4": "[\"10.34.108.123\"]",
"ipv6": "[\"fe80::5054:ff:fe88:62af%ens3\", \"2620:52:0:226c:5054:ff:fe88:62af\"]",
"netmask": "[\"255.255.255.0\"]",
"role": "[\"tendrl/node_c692ee35-561e-4c72-a31e-22361b2040f2\", \"tendrl/node\"]",
```

## Expected Result

All list values are provided as a list of strings, so that one can process that data in json format as expected, so that:

Search for lists encoded as string values finds nothing:

```
$ grep '\[' getnodelist.response.pretty.json | grep '"\[' | wc -l
0
```

and values are provided as a proper json lists instead:

```
$ grep '\[' getnodelist.response.pretty.json | grep '"\[' | sed 's/^ *//g' | head -1
"tags": ["provisioner/ceph", "tendrl/central-store", "tendrl/server", "tendrl/node_a6662d3c-4757-45c1-b3d8-4565cb4b0a1c", "tendrl/monitor", "tendrl/node"],
```

## Additional information

Moreover there are other related inconsistencies in data provided by the api:

```
$ grep device_files getnodelist.response.pretty.json | head -1
                "device_files": "/dev/vda1, /dev/disk/by-id/virtio-b5d6f749a23db96b-part1, /dev/disk/by-path/virtio-pci-0000",
```

here the list are provided as a string value, with items separated by commas - which is a better option compared to json escaped encoded string, but it could be provided as a list as well

**Comment by r0h4n** [comment]
@anivargi is this done?

**Comment by anivargi** [comment]
Fixed in https://github.com/Tendrl/api/pull/246
