### ISSUE TITLE
New entity is not present in the api replies for some time after it's create task finished

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#221]
New entity (such as cluster, brick, volume, ...) is not immediately present in api replies when asking for list of such entities (list clusters, bricks, volumes ...). It actually takes some time after related create task finished for the new entity to appear.

Please note that this problem is generic, and affects all entities such as pools, rbds, files shares, bricks, volumes and so on.

The root cause of the problem seems to be incorrect definition if the finished state of a task, which doesn't seem to include getting consensus/synchronization withing Tendrl itself.

## Version

```
# rpm -qa 'tendrl-*'
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
```

## Reproducer - example one

1. Install Tendrl Server using tendrl-ansible
1. Start import or create a cluster
2. Wait till the job is finished
3. Look for available clusters

### Actual results

The cluster is not present in `GetClusterList` response. It takes several seconds till the cluster appears.

### Expected results

The cluster should be present in the list when the task finishes. Could be present before the task ends though. 

## Reproducer - example two

1. Install Tendrl Server using tendrl-ansible and other tendrl machines (storage nodes) from scratch
2. Create gluster cluster
3. Try to create a gluster volume
4. Follow suggestion of the wizard and create bricks
5. Try to create gluster volume again, immediately when the create bricks task finishes

### Actual Result

When create gluster volume wizard is reached, web ui warns you that there are no bricks, which are required to create new volume, and provides a convenient link to create bricks.

When create bricks tasks finishes with success, you go to the create volume again and try to create volume, now with bricks - but the wizard warns you again: there are no bricks available.

This happens because while the bricks has been actually created, it takes some time for tendrl to update itself and handle them. Unfortunately this is super confusing in this case.

### Expected Result

The create bricks task should finish only when the tendrl is aware of them , so that it's immediately possible to use them to create a volume.

**Comment by r0h4n** [comment]
1) For objects inside a cluster (like pool, volume, rbd), Tendrl will now not mark the CRUD job as finished until the CRUD has actually happened on the SDS


2) For Create Cluster and other day 1 flows like import, expand. Here is the tracking bug where this issue will be fixed https://github.com/Tendrl/commons/issues/642

**Comment by mbukatov** [comment]
Based on the information in previous comment and details in related issue https://github.com/Tendrl/commons/issues/642, the design problem described there is expected to be fixed now.
