### ISSUE TITLE
cluster import fails and there are no messages after it fails

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#227]
Gluster cluster import fails and there are no messages after it fails. It is the same as https://github.com/Tendrl/api/issues/219
Reproducer:
1. Install tendrl and create gluster cluster from 4 nodes outside of tendrl
2. restart all nodes
3. start `glusterd` service
4. create `GlusterImportCluster` job from the cluster via UI
5. job fails without messages

`/var/log/messages` from gluster nodes and server:
[varlogmessages.zip](https://github.com/Tendrl/api/files/1108551/varlogmessages.zip)

Tested with:
tendrl-alerting-1.4.2-1.el7.centos.noarch
tendrl-api-1.4.2-1.el7.centos.noarch
tendrl-api-httpd-1.4.2-1.el7.centos.noarch
tendrl-commons-1.4.2-1.el7.centos.noarch
tendrl-dashboard-1.4.2-1.el7.centos.noarch
tendrl-node-agent-1.4.2-1.el7.centos.noarch
tendrl-performance-monitoring-1.4.2-1.el7.centos.noarch

**Comment by mbukatov** [comment]
@fbalak could you add a package versions?

**Comment by fbalak** [comment]
@mbukatov done

**Comment by mbukatov** [comment]
@fbalak is it ok that this issue has been closed?

**Comment by fbalak** [comment]
@mbukatov I haven't encounter this issue for some time. If I find it I will ask to reopen this again.
