### ISSUE TITLE
documentation - describe Bricks Mapping

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#228]
I do not understand from documentation what is [Bricks Mapping](https://github.com/Tendrl/api/blob/develop/docs/bricks.adoc) doing. Could there be described what Bricks Mapping does and what can be achieved? What {"67afa32d-883b-45f3-b331-bc96ecd010ba":null} in API call means? What are hostnames in job output?

**Comment by shtripat** [comment]
@nnDarshan ^^^
