### ISSUE TITLE
Incompatibility of documentation and API

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#23]
Request URLs for gluster volume creation via API are not same as URLs specified in documentation [1].
For example currently works
`POST /:cluster_id/GlusterCreateVolume`
instead of
`POST /cluster/:cluster_id/volume/create`
Json data that is sent to API in POST requests is also different.
Either the documentation or API implementation should be corrected.

[1] https://github.com/Tendrl/documentation/blob/master/api/gluster-create-volume-example.adoc

**Comment by anivargi** [comment]
Hi,

I am working on updating the existing documentation for all the flows.

> On 22-Nov-2016, at 13:43, Filip Balák <notifications@github.com> wrote:
> 
> Request URLs for gluster volume creation via API are not same as URLs specified in documentation [1].
> For example currently works
> POST /:cluster_id/GlusterCreateVolume
> instead of
> POST /cluster/:cluster_id/volume/create
> Json data that is sent to API in POST requests is also different.
> Either the documentation or API implementation should be corrected.
> 
> [1] https://github.com/Tendrl/documentation/blob/master/api/gluster-create-volume-example.adoc
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Anup Nivargi

**Comment by anivargi** [comment]
@fbalak can I close this?

**Comment by fbalak** [comment]
@anivargi I would wait with closing until pull request with correction will be merged.

[1] https://github.com/Tendrl/documentation/pull/62
