### ISSUE TITLE
Remove monitoring API proxy code

### ISSUE THREAD

**Issue by anivargi** [Tendrl/api#233]
The monitoring code is not not needed as we are moving towards Grafana+Graphite based integration for displaying monitoring data

**Comment by r0h4n** [comment]
Is this done @anivargi ?

**Comment by anivargi** [comment]
@r0h4n No, not yet, but will be part of next release.

**Comment by anivargi** [comment]
Was fixed part of https://github.com/Tendrl/api/tree/release/1.5.1
