### ISSUE TITLE
Disable a Tendrl User

### ISSUE THREAD

**Issue by a2batic** [Tendrl/api#238]
According to the [mockup](https://redhat.invisionapp.com/share/KNB25OEQT#/screens/226063808), there is a functionality of enabling and disabling user.

tendrl-ui-bug-id: https://github.com/Tendrl/ui/issues/556

**Comment by nthomas-redhat** [comment]
@a2batic , I am closing this issue as we already decided not to implement this.

**Comment by mkudlej** [comment]
@nthomas-redhat could you please initiate design document change? Is there any link-able discussion?
@julienlim Are you aware of this, please? Do you plan to change design according this decision?

**Comment by julienlim** [comment]
@Tendrl/qe Yes, I'm aware that enable/disable user is not part of the release.  We can update the design if needed to say future or out of scope.  I'd rather not take it out as it'll probably have to be put back in the design in the future.

@mcarrano - can you please update the design to note that enable/disable user is out-of-scope / FUTURE feature.  Thanks.

**Comment by mcarrano** [comment]
I placed a note on the wireframe to communicate that this functionality is out of scope and the Status column and related actions should be hidden. See updates here https://redhat.invisionapp.com/share/8QCOEVEY9  on Users page.

**Comment by julienlim** [comment]
@mcarrano thanks for adding the note.

@Tendrl/qe @Tendrl/tendrl_frontend
