### ISSUE TITLE
Job_id status

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#24]
Api returns job_id after volume creation or deletion requests are sent. There should be some api request that allows getting status of job_id.

**Comment by shtripat** [comment]
@anivargi can you please respond to this?

**Comment by brainfunked** [comment]
This is being implemented as part of https://github.com/Tendrl/specifications/issues/55.

**Comment by fbalak** [comment]
Tested with tendrl-api-1.2-02_01_2017_01_51_04.noarch. There is implemented hostname/api/1.0/jobs call which returns list of jobs.
