### ISSUE TITLE
/api/1.0/clusters/<cluster_id>/import API doc requires update

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/api#248]
Doc says { "enable_volume_profiling": "yes" } is the paramaeter to be passed. But it should be { "Cluster.enable_volume_profiling": "yes" }

**Comment by nthomas-redhat** [comment]
Or this should be handled by API internally?

**Comment by anivargi** [comment]
@nthomas-redhat the API directly updates etcd, so just `"enable_volume_profiling": "yes"` is enough.

**Comment by anivargi** [comment]
Sorry got confused, @nthomas-redhat I think the UI needs to send it as you mentioned for import, but I have mentioned for how individually it needs to be updated

**Comment by anivargi** [comment]
Fixed https://github.com/Tendrl/api/pull/267
