### ISSUE TITLE
Endpoint for exposing cluster specific host information for hosts in a cluster

### ISSUE THREAD

**Issue by brainfunked** [Tendrl/api#249]
This issue is related to the discussion on https://github.com/Tendrl/ui/issues/534.

[The hosts list view](https://redhat.invisionapp.com/share/2RCOE72PE#/screens/244735173) inside a cluster needs to scale to 128 hosts with 36 bricks each for milestone 3, with the eventual target being 60 bricks per host. Would it make sense to implement an API call which allows fetching of cluster specific host information ([cluster specific storage utilisation](https://github.com/Tendrl/gluster-integration/issues/378) and brick information for the host, presently), individually, only when requested by the end-user?

**Comment by anivargi** [comment]
Fixed as part of https://github.com/Tendrl/api/pull/265
