### ISSUE TITLE
EPEL dependency for deployment via packages

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#25]
Tendrl upstream rpm packages should not depend on any package from EPEL repository.
Packages required from EPEL:
- rubygem-rack-protection                                                                                                                                                     
- rubygem-rack                                                                                                                                                                
- rubygem-tzinfo                                                                                                                                                             
- rubygem-activesupport                                                                                                                                                      
- rubygem-i18n                                                                                                                                                              
- rubygem-thread_safe

**Comment by r0h4n** [comment]
Tendrl targets to create rpms for fedora, centos7, rhel7, I guess you are trying to say that the rhel7 rpms should not depend on EPEL?

Because using EPEL is fine for Tendrl in case of fedora or centos7

**Comment by anivargi** [comment]
@fbalak can i close this?

**Comment by mbukatov** [comment]
@anivargi yes, qe wanted to verify that the decision to depend on packages from epel is acknowledged
