### ISSUE TITLE
Configure Webhook for ci.centos.org

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#252]
Could you please configure webhook to `https://ci.centos.org/github-webhook/` for this repo, which will trigger package build for each commit in master branch?

_Instruction copied from [1]:_
Add a Webhook to your repository pointing at https://ci.centos.org/github-webhook/
2. On your Github Project page, choose 'Settings'
3. Navigate to the 'Webhooks and Services' tab
4. Choose 'Add a webhook'
  Paste `https://ci.centos.org/github-webhook/` in the Payload URL

[1] [Integrating Jobs on ci.centos.org with Github - Mode 1: Trigger on Every Commit](https://wiki.centos.org/QaWiki/CI/GithubIntegration#head-d79a4b6b575198db2dc5395400f2c40a65cc1eb3)

**Comment by r0h4n** [comment]
Done
