### ISSUE TITLE
user can steal session token from another user

### ISSUE THREAD

**Issue by mkudlej** [Tendrl/api#256]
Etcd is not hardened and user can steal another user access token. User can increase his permissions by this if there is logged in user with higher permissions.

Reproducer:
```curl http://_hostname_:2379/v2/keys/_tendrl/access_tokens``` where ```_hostname_``` is FQDN where is Etcd.

etcd-3.1.9-1.el7.x86_64
glusterfs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-api-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-cli-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-client-xlators-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-fuse-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-libs-4.0dev-0.85.gitea48cae.el7.centos.x86_64
glusterfs-server-4.0dev-0.85.gitea48cae.el7.centos.x86_64
httpd-2.4.6-45.el7.centos.4.x86_64
httpd-tools-2.4.6-45.el7.centos.4.x86_64
python-etcd-0.4.5-1.noarch
python-httplib2-0.7.7-3.el7.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-gluster-integration-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch

Tendrl 1.5.1

**Comment by anivargi** [comment]
We are depending on the etcd authorization to prevent access to tokens directly.

**Comment by mkudlej** [comment]
@anivargi Right now Etcd authentication is not specified in documentation. I think this issue is valid until there is any authentication in Etcd in documentation.

**Comment by anivargi** [comment]
@mkudlej I think this is a issue which needs to be addressed at the Etcd host level, where only a certain whitelisted IP's can access etcd part from having authentication for Etcd, there is no other way to manage this on the API level.

**Comment by r0h4n** [comment]
Related issues (for ETCD cert based auth) are linked to this issue. Once the cert based auth for ETCD is implemented via the linked issues, this issue will be no longer valid.
