### ISSUE TITLE
Admin user should not be able to delete himself

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#257]
User can delete itself.

**Comment by anivargi** [comment]
@ltrilety please clarify what you mean exactly?

**Comment by ltrilety** [comment]
@anivargi not sure what's here to clarify more. Seems to me that any user should not be able to remove itself. Anyway reproduction steps follows:

1. log as admin - `api/1.0/login` `POST` call, remember allocated access_token
2. delete admin user - `api/1.0/users/admin` DELETE call with access_token from previous step

User is deleted, all open related sessions are terminated.
