### ISSUE TITLE
Normal user should not be able to perform user management

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#258]
User with Normal (power user) role can create a new user even a new user with admin role.

**Comment by anivargi** [comment]
@ltrilety we are not addressing this in the upcoming release.
We are sticking to https://github.com/Tendrl/api/blob/master/docs/authorizaton.adoc

**Comment by anivargi** [comment]
I misunderstood the issue as normal user should be able to create admin users, so reopening.

**Comment by anivargi** [comment]
Fixed as part of https://github.com/Tendrl/api/pull/260
