### ISSUE TITLE
troubleshoot when import cluster fails

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#266]
There should be some troubleshoot guide with instructions what can be done if cluster import is not successful e.g. some node is missing etc.

It will be good if there will be described some way how to remove cluster from tendrl.

**Comment by anivargi** [comment]
Please add the issue to documentation repo.

**Comment by ltrilety** [comment]
@anivargi right, documentation issue created https://github.com/Tendrl/documentation/issues/94
