### ISSUE TITLE
puma - tendrl-api consumes huge amount of memory - possible memory leak?

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#271]
Under some circumstances, puma/tendrl-api consumes huge amount of RAM (for example 17GB on system with total of 23GB) and didn't release it.

**Reproducer:**
1. Install and configure Gluster cluster with at least one volume.
1. Install and configure Tendrl server and node agents.
1. Measure the consumed RAM (you might get inspired by following two scripts)
This first script just print time and memory/swap statistics for whole system once peer 5 minutes.
 ```
while true; do
  date "+[%H:%M:%S]";
  free -h;
  sleep 300;
done
```
The second script prints time and % of CPU and % of memory used by *puma - tendrl-api* process once peer 5 minutes.
```
while true; do
  echo -ne "$(date '+[%H:%M:%S]')\t";
  ps -p $(echo $(ps aux | grep [t]endrl-api | awk '{print $2}') | sed 's/ /,/') -o %cpu,%mem,cmd -h;
  sleep 300;
done
```
4. Import Gluster cluster into Tendrl.
1. Leave it running for bunch of hours (1 day, to be sure).
1. Open Tendrl web UI on *Clusters* page.
1. Reload the page multiple times (do not wait till the page is fully loaded, just reload it while it is still loading).

**Result**
Total memory consumption during 48 hours:
![memory-usage](https://user-images.githubusercontent.com/4759779/30364056-e5ad92e6-9862-11e7-9759-4ecc32d4d5d1.png)

Memory consumption of *puma - tendrl-api*:
![htop_screenshot](https://user-images.githubusercontent.com/4759779/30364063-e8ccfc6e-9862-11e7-88a8-e8e40e445b61.png)

**Version-Release number of selected components:** 
```
etcd-3.1.9-1.el7.x86_64
python-etcd-0.4.5-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
rubygem-puma-3.6.0-1.el7.centos.x86_64
tendrl-api-1.5.1-1.el7.centos.noarch
tendrl-api-httpd-1.5.1-1.el7.centos.noarch
tendrl-commons-1.5.1-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.1-1.el7.centos.noarch
tendrl-node-agent-1.5.1-1.el7.centos.noarch
tendrl-ui-1.5.1-1.el7.centos.noarch
```

**Comment by anivargi** [comment]
Fixed https://github.com/Tendrl/api/pull/276/files
We have added a puma config to preload app which enables copy on write.
