### ISSUE TITLE
Missing documentation for api call clusters/<CLUSTER-ID>/profiling

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#273]
There is no documentation for *clusters profiling* API PUT call:
```http://<TENDRL-SERVER>/api/1.0/clusters/<CLUSTER-ID>/profiling``` with data ```{"enable_volume_profiling":"yes|no"}```

**Comment by anivargi** [comment]
https://github.com/Tendrl/api/blob/master/docs/clusters.adoc#enable-disable-profiling
