### ISSUE TITLE
Cluster.enable_volume_profiling key error

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#274]
API doc says that for import cluster there should be `{"enable_volume_profiling": "yes"}` the same as for enable/disable profiling call. So it seems to be right. However when user tries to import a cluster with this it always fails with error: `KeyError: 'Cluster.enable_volume_profiling'`

**Comment by shtripat** [comment]
Yes. The parameter name should be `Cluster.enable_volume_profiling`

**Comment by ltrilety** [comment]
@shtripat I strongly suggest to unify this across all API calls and my humble opinion is that `enable_volume_profiling` looks better.

**Comment by anivargi** [comment]
Fixed in https://github.com/Tendrl/api/pull/277
