### ISSUE TITLE
Volumes API is returning incomplete response

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#289]
API - clusters/{cluster_id}/volumes is returning incomplete response. Attributes like vol_id and name etc are missing. 

API response - 

> {
"volumes":[
{
"hash":"9db4f15f5f5c6e7db7e27fc9fbe63980",
"updated_at":"2017-09-18 10:10:37.980344+00:00",
"rebalancedetails":{},
"vol_id":"47d49ca4-9cd8-4453-8b95-42dd513a3ed5"
},

**Comment by anivargi** [comment]
@shtripat This is the same issue as before, Etcd does not have the volume details, hence the issue.

**Comment by rishubhjain** [comment]
@gnehapk @anivargi Can you pass me the instance id?, may be I can check for volume details and restart gluster-integration to get the volume details in etcd.

**Comment by anivargi** [comment]
@gnehapk Is this still a issue?

**Comment by gnehapk** [comment]
@anivargi It seems to be fixed with the latest build. Closing this issue.
