### ISSUE TITLE
[selinux] postinstall and postuninstall scripts should not contain `restorecon -Rv /`

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#291]
Postinstallation and postuninstallation scripts from following packages ``tendrl-grafana-selinux``, ``tendrl-server-selinux`` should not contain command ``restorecon -Rv /``. Rrestoring SELinux security contexts on whole filesystem will take very long time and might broke something else.

The target path should be more precisely specified just to relevant/affected files, not widely to whole filesystem.

```
# rpm -qp --scripts tendrl-server-selinux-1.5.2-1.el7.centos.noarch.rpm
# rpm -qp --scripts tendrl-grafana-selinux-1.5.2-1.el7.centos.noarch.rpm 
```

**Comment by mkudlej** [comment]
@Tendrl/tendrl-core  I vote for marking this issue as high priority one.

**Comment by mbukatov** [comment]
This issues will be addressed during my work on moving selinux code into single repository tendrl-selinux.

**Comment by r0h4n** [comment]
@TimothyAsir What is the update on this issue?

**Comment by TimothyAsirJeyasing** [comment]
We are planning to move the Selinux package build script and the policy int separate repo that will take care of these issues.

**Comment by anivargi** [comment]
@dahorak can we close this?

**Comment by mbukatov** [comment]
I will close this when my work on tendrl-selinux repo is done.

**Comment by TimothyAsirJeyasing** [comment]
@mbukatov Shall we close this issue now?
