### ISSUE TITLE
Can not change user role

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#298]
I created users thardy and thardy2. thardy is admin and thardy2 is normal user. I am logged as default admin user.
When I call [Update User API call](https://github.com/Tendrl/api/blob/master/docs/users.adoc#update-user) on user thardy:
```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer d03ebb195dbe6385a7caeda699f9930ff2e49f29c381ed82dc95aa642a7660b8' -XPUT -d '{"role":"normal"}' http://127.0.0.1/api/1.0/users/thardy
```
than response is:
```
{
    "email": "testmail@tendrl.org",
    "username": "thardy",
    "name": "Tom Hardy",
    "role": "admin",
    "email_notifications": false
}
```
and user role is not changed. Role should be `normal`.

When I call:
```
curl -H 'Content-Type: application/json' -H 'Authorization: Bearer d03ebb195dbe6385a7caeda699f9930ff2e49f29c381ed82dc95aa642a7660b8' -XPUT -d '{"role":"admin"}' http://127.0.0.1/api/1.0/users/thardy2
```
then response is:
```
{
    "email": "thardy@tendrl.org",
    "username": "thardy2",
    "name": "Tom Hardy",
    "role": "normal",
    "email_notifications": false
}
```
but when I list users than the user role is not changed. Role should be `admin`.

Tested with:
tendrl-api-httpd-1.5.2-1.el7.centos.noarch
tendrl-commons-1.5.2-1.el7.centos.noarch
tendrl-api-1.5.2-1.el7.centos.noarch
tendrl-ui-1.5.2-1.el7.centos.noarch
tendrl-node-agent-1.5.2-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.2-1.el7.centos.noarch
tendrl-grafana-plugins-1.5.2-1.el7.centos.noarch
tendrl-notifier-1.5.2-1.el7.centos.noarch

**Comment by nthomas-redhat** [comment]
@anivargi , I think what we discussed earlier was to not allow the user role change

**Comment by anivargi** [comment]
@nthomas-redhat Yes.
@fbalak Updating role of existing user is not allowed.

**Comment by ltrilety** [comment]
@anivargi Actually the idea was that user cannot change the role for himself/herself.
