### ISSUE TITLE
Admin user can not delete another admin user

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#299]
I have users admin and thardy. Both are admins. I am logged as admin.
I try to [delete user thardy via API as documented](https://github.com/Tendrl/api/blob/master/docs/users.adoc#delete-user) but the response is `403 Forbidden`. Normal users can be removed. I think that there should be some way how to delete admin users.

Tested with:
tendrl-api-httpd-1.5.2-1.el7.centos.noarch
tendrl-commons-1.5.2-1.el7.centos.noarch
tendrl-api-1.5.2-1.el7.centos.noarch
tendrl-ui-1.5.2-1.el7.centos.noarch
tendrl-node-agent-1.5.2-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.2-1.el7.centos.noarch
tendrl-grafana-plugins-1.5.2-1.el7.centos.noarch
tendrl-notifier-1.5.2-1.el7.centos.noarch

**Comment by anivargi** [comment]
@fbalak Admin users cannot be deleted by other admin users.

**Comment by ltrilety** [comment]
@anivargi in other words admin users cannot be deleted. That's very strange behavior. I remember that there was an issue when user can remove himself/herself and so delete the last admin user, but that's it. No requirement which rejects deletion of any admin user.

**Comment by anivargi** [comment]
@ltrilety That is the scope for this release, admin users cannot delete admin users.

Regarding roles, we have limited updating any roles by any user.
