### ISSUE TITLE
Internal Server Error when user does not exist

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#300]
If I use API calls as documented for user [deletion](https://github.com/Tendrl/api/blob/master/docs/users.adoc#delete-user) or [update](https://github.com/Tendrl/api/blob/master/docs/users.adoc#update-user) on user that does not exist then the response from server is `500 Internal Server Error`. Response should be `404 Not Found`.

Tested with:
tendrl-api-httpd-1.5.2-1.el7.centos.noarch
tendrl-commons-1.5.2-1.el7.centos.noarch
tendrl-api-1.5.2-1.el7.centos.noarch
tendrl-ui-1.5.2-1.el7.centos.noarch
tendrl-node-agent-1.5.2-1.el7.centos.noarch
tendrl-monitoring-integration-1.5.2-1.el7.centos.noarch
tendrl-grafana-plugins-1.5.2-1.el7.centos.noarch
tendrl-notifier-1.5.2-1.el7.centos.noarch

**Comment by anivargi** [comment]
https://github.com/Tendrl/api/pull/314

**Comment by fbalak** [comment]
Ok.
Tested with:
```
tendrl-ansible-1.5.3-20171009T123017.9a9a956.noarch
tendrl-node-agent-1.5.3-20171013T062755.31f55de.noarch
tendrl-grafana-plugins-1.5.3-20171012T151314.4c1bec1.noarch
tendrl-monitoring-integration-1.5.3-20171012T151314.4c1bec1.noarch
tendrl-api-httpd-1.5.3-20171012T100843.aa0dba3.noarch
tendrl-notifier-1.5.3-20171011T200310.3c01717.noarch
tendrl-commons-1.5.3-20171011T195629.890684b.noarch
tendrl-api-1.5.3-20171012T100843.aa0dba3.noarch
tendrl-ui-1.5.3-20171012T142223.125d75e.noarch
```
