### ISSUE TITLE
Required: Internal profiling for tendrl-api

### ISSUE THREAD

**Issue by r0h4n** [Tendrl/api#301]
Similar to profiling Tendrl backend services https://github.com/Tendrl/documentation/wiki/Tendrl-profiling

It is time we start internal profiling the tendrl-api  (eg: Number of function calls, average time per call etc etc)

Eg: https://github.com/ruby-prof/ruby-prof

**Comment by anivargi** [comment]
https://github.com/Tendrl/api/pull/305
