### ISSUE TITLE
support for etcd client-server tls authentication

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#307]
Since [we are planning to use](https://github.com/Tendrl/documentation/wiki/Tendrl-with-a-secure-etcd-cluster) [etcd client-server tls authentication](https://coreos.com/etcd/docs/latest/op-guide/security.html), we need to add support of this into tendrl-api as well.

This will require to add new configuration options for:

* etcd_ca_cert_file (for /path/to/ca_cert_file.pem)
* etcd_cert_file (for /path/to/client_cert_file.pem)
* etcd_key_file (for /path/to/client_key_file.pem)

## Related Issues

* This blocks merge of https://github.com/Tendrl/tendrl-ansible/issues/42

**Comment by anivargi** [comment]
https://github.com/Tendrl/api/pull/310
