### ISSUE TITLE
[documentation] puma is used as a web server

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#32]
In the default installation (as suggested by README file and Gemfile.lock file), [puma websterver](http://puma.io/) is installed and configured to serve the Tendrl API. At first sight, this seems to be extraneous. Is puma web server really needed for the Tendrl API to run?

**Comment by anivargi** [comment]
@mbukatov We use Puma as a application server, in development mode you don;t need a web server like Apache for ex., hence we just need the application server. 

When we are running in production, we need the web server sitting on top of the application server and hence we use Apache + Puma, we could just use only Puma without Apache, but having a Web server sit on top of a application server has its own benefits like virtual hosts, url rewriting etc.

**Comment by mbukatov** [comment]
@anivargi So puma server is required, ok. I was not sure if using just apache without puma is valid scenario for running tendrl-api.

**Comment by mbukatov** [comment]
Could you make clear the role of puma webserver in the documentation? Eg. mention the purpose of puma and the fact that one can't run tednrl-api without it, along with the reasoning for this.
