### ISSUE TITLE
API for fetching Events and task per cluster level

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#329]
UI needs API for fetching events and task per cluster level as per Concept B design.

- https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/251481034
- https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/251481034

**Comment by cloudbehl** [comment]
Linking: https://github.com/Tendrl/ui/pull/682

**Comment by r0h4n** [comment]
@anivargi  is this done?

**Comment by anivargi** [comment]
@r0h4n I was told this is part of next release.

**Comment by TimothyAsirJeyasing** [comment]
import_job_id under each cluster refers to a particular task.

**Comment by gnehapk** [comment]
@r0h4n The API call to fetch tasks per cluster should be like - /api/1.0/clusters/{cluster_id}/jobs and for events per cluster should be like /api/1.0/clusters/{cluster_id}/notifications

**Comment by gnehapk** [comment]
API is now there to fetch cluster specific tasks and events. Hence, closing this issue.
