### ISSUE TITLE
Volumes and Alerts count in '/api/1.0/clusters' API

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#341]

**Comment by shtripat** [comment]
@gnehapk volume count is available under GlobalDetails of cluster. Need to include the same in API output for cluster. Similarly there is `alerting/clusters/{int-id}` which would needed to exposed through API. Tagging @GowthamShanmugam for more details on cluster level alerts count.

**Comment by TimothyAsirJeyasing** [comment]
@gnehapk both volume count and alert count is already available in the api output for cluster

1) volume count : ['clusters'][ id ]['globaldetails']
'globaldetails': {'connection_active': '0',
                   'connection_count': '0',
                   'hash': '98ee577c4ddea839fe535874ed421ad2',
                   'peer_count': '3',
                   'status': 'unhealthy',
                   'updated_at': '2018-01-31 08:25:29.882300+00:00',
                   'vol_count': '1',
                   'volume_up_degraded': '0'},

2) alert count: ['clusters'][ id ]['alert_counters']['warning_count']
ex:. {'alert_counters': {'hash': 'f3ed56d00f83eb251c719911aedcd1d4',
                    'integration_id': 'e372c01c-5022-41ce-9412-e96038bca305',
                    'updated_at': '2018-01-29 06:44:03.454402+00:00',
                    'warning_count': '3'}

**Comment by GowthamShanmugam** [comment]
@TimothyAsir  this is cluster alert coun , I think @gnehapk is asking volume alert count

**Comment by gnehapk** [comment]
@TimothyAsir Thanks for the update.
@GowthamShanmugam  I have asked cluster's alert and volume count.

**Comment by r0h4n** [comment]
@gnehapk It seems that the api already returns what you require, can you close this issue?
