### ISSUE TITLE
Question: Should we do some validation when creating bricks via GlusterCreateVolume api call?

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#35]
During testing I noticed that `GlusterCreateVolume` api call creates            
brick directories for all bricks passed to the call. So for example,            
when one passes `node1.example.com:/mnt/brick` as one of the bricks to the      
call (which is an invalid input wrt gluster conventions), `/mnt/brick`           
directory is created.                                                           
                                                                                
The assumption on the Gluster side is that a brick directory is created in      
the root directory of brick volume (usually with xfs filesystem), which is      
hosted on a dedicated disk.                                                     
                                                                                
Which brings me to the question: What are the assumptions on for                
`GlusterCreateVolume` call? Who and when is expected to create xfs filesystem   
for the brick? Would it make sense to do some validation during the process?    
                                                                                
Eg. should passing `/mnt/brick` as a brick be processed with success when there 
is no xfs brick filesystem on `/mnt`?                                           
                                                                                
Moreover: maybe we may consider to reject brick paths which points to system    
directories?

[1] https://github.com/Tendrl/documentation/blob/c26ccba15091efd70de41c54929f5f710626b8ec/api/gluster-volume-examples.adoc

**Comment by mkudlej** [comment]
I think creating volume cannot have side effects like creating directories for bricks. If API function has name ```GlusterCreateVolume``` it should only create Gluster volume from parameters.
Also I think there can be checks if volume can be created.
I expect that for creating bricks there will be different API function.

**Comment by shtripat** [comment]
@mkudlej regarding creation of directories while volume creation is actually a gluster feature. Gluster can create first level directories if they dont exist and passed as brick mount path. For example a dir /mnt/vol1_brick1 doesnt exist but /mnt is actually existing. In this case if a volume creation passes one of the bricks as /mnt/vol1_brick1, gluster would actually create the directory and would go ahead with volume creation.

But if two levels of dir name is passed and it doesnt exist (e.g. /mnt/bricks/vol1_brick1 and only /mnt exists and no /mnt/bricks and /mnt/bricks/vol1_brick1) gluster would not create the dir and creation of volume would fail saying dirrectory doesnt exist.

@fbalak regarding your question "What are the assumptions on for GlusterCreateVolume call? Who and when is expected to create xfs filesystem for the brick? Would it make sense to do some validation during the process?" the brick provisioning is actually a separate step from raw disks where the disk is formatted with xfs and then mounted in a defined path. Now this defined path can be passed as brick for volume creation. Most of your question would be answered I feel once brick provisioning feature lands in tendrl. 
Regarding validations while volume creations, yes there could be few standardization followed like mount paths for the bricks should not be system dirs,  they should be mounted in certain predefined path etc. But yes these things could be added to the flow once brick provisioning lands up here.

Hope this clarifies the doubts here and if so this question we can close and refer while brick provisioning work.

**Comment by mkudlej** [comment]
@shtripat Do I understand it right that this is feature of Gluster itself and Tendrl doesn't create thos directories?

**Comment by shtripat** [comment]
@mkudlej thats true..

**Comment by shtripat** [comment]
@mkudlej thats true..

**Comment by shtripat** [comment]
@mkudlej @fbalak can we close this ?

**Comment by r0h4n** [comment]
Closing this one, let me know if needs to be reopened
