### ISSUE TITLE
Host IP address required in API

### ISSUE THREAD

**Issue by a2batic** [Tendrl/api#358]
According to design[1], `\clusters\{cluster_id}\nodes`, should return an IP address for each node.
[1] https://redhat.invisionapp.com/share/8QCOEVEY9#/screens/278907431

**Comment by a2batic** [comment]
Tendrl-ui-bug-id: https://github.com/Tendrl/ui/issues/808

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/node-agent/issues/718

No change required in tendrl-api
