### ISSUE TITLE
Unmanage API requires unnecessary parameter cluster_id

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#365]
URI for cluster unmanage API call looks like: `hostname/api/1.0/{imported_cluster_id}/unmanage` and it requires to send data in format: `{"cluster_id":"{imported_cluster_id}"}`. If the json with these data is not provided then the call is not processed:
```
$ curl -XPOST -H "Authorization: Bearer access_token" -H "Content-Type: application/json" hostname/api/1.0/clusters/{imported_cluster_id}/unmanage
{"errors":{"message":"Invalid JSON received."}}
```
but when the `cluster_id` parameter is provided, it works:
```
$ curl -XPOST -H "Authorization: Bearer access_token" -H "Content-Type: application/json" -d '{"cluster_id":"{imported_cluster_id}"}' hostname/api/1.0/clusters/{imported_cluster_id}/unmanage
{"job_id":"53474cf0-72d1-4edc-854f-a63e91e17956"}
```
User should not be required to enter `cluster_id` in json data that are sent with API request as this information is already part of the URI of the API call.

Tested with:
```
tendrl-ansible-1.5.5-1.el7.centos.noarch
tendrl-api-1.6.0-1.el7.centos.noarch
tendrl-api-httpd-1.6.0-1.el7.centos.noarch
tendrl-commons-1.6.0-1.el7.centos.noarch
tendrl-grafana-plugins-1.6.0-1.el7.centos.noarch
tendrl-grafana-selinux-1.5.4-2.el7.centos.noarch
tendrl-monitoring-integration-1.6.0-1.el7.centos.noarch
tendrl-node-agent-1.6.0-1.el7.centos.noarch
tendrl-notifier-1.6.0-1.el7.centos.noarch
tendrl-selinux-1.5.4-2.el7.centos.noarch
tendrl-ui-1.6.0-1.el7.centos.noarch
```

**Comment by shtripat** [comment]
@fbalak I find that actually we don't need to pass `cluster_id` in request body for import as well as un-manage. But yes an empty dictionary is required to be passed in request as below

```
curl -XPOST -H "Authorization: Bearer access_token" -H "Content-Type: application/json" -d '{}' hostname/api/1.0/clusters/{imported_cluster_id}/unmanage
```

@r0h4n it there a way to omit this empty dict thingy in ruby??

**Comment by r0h4n** [comment]
@shirshendu Could you help out here?

**Comment by shirshendu** [comment]
@r0h4n sure, having a look

**Comment by shirshendu** [comment]
@shtripat We've removed the unmanage endpoint's spec here: https://github.com/Tendrl/api/commit/c2ea06e7f892dde543679a24d8ed2184a23e85ae#diff-bb83651c69e2ac223590fb60961ba07dL51
Did the functionality of the endpoint change?

**Comment by shtripat** [comment]
@shirshendu just to avoid unit test failure I removed it.

**Comment by shirshendu** [comment]
No worries. Did some more digging. This spec was basically a failing spec that got merged into master along with the unmanaged API code.
To make the spec work, we'll need a flow definition for `UnmanageCluster` to be added to the `spec/fixtures/definitions/tendrl_definitions_node_agent.json` file.
@r0h4n Who can help me with getting the correct flow definition?

**Comment by shtripat** [comment]
@shirshendu all we need from this flow is that after submitting a POST request `/clusters/{int-id}/unmanage` we should get a task-id in output. I feel even import cluster we expect the same output. The only difference between import and unmanage is that unmanage doesn't need any other input than integration-id in request URL.

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/api/pull/369
