### ISSUE TITLE
is_managed is yes when unmanage process is going on

### ISSUE THREAD

**Issue by a2batic** [Tendrl/api#366]

**Comment by shtripat** [comment]
@a2batic This issue would be resolved after recent changes in import cluster `flow. is_managed = 'yes'` will not be set again and again during gluster-integration syncs anymore.

Refer https://github.com/Tendrl/commons/pull/827 and https://github.com/Tendrl/gluster-integration/pull/565

So once un-manage cluster flow sets the `cluster.is_managed = 'no'` in starting it will remain the same.
Makes you happy :)

**Comment by a2batic** [comment]
@shtripat Thankyou. We are using other flags for checking various things, but for https://github.com/Tendrl/ui/issues/836 `is_managed` flag might be creating issues because sometimes `current_job` is an empty string and context switcher directly use data sent from API. But, its not a blocker for UI.

Thanks for looking into it.

**Comment by r0h4n** [comment]
Comment if this needs to be reopened

@a2batic
