### ISSUE TITLE
etcd related configuration - possible unification?

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#37]
I noticed that there is a configuration file for access details to etcd instance: /etc/tendrl/etcd.yml

Excerpt from [config/etcd.sample.yml](https://github.com/Tendrl/tendrl-api/blob/master/config/etcd.sample.yml):

```
---
:test:
  :base_key: ''
  :host: '127.0.0.1'
  :port: 2379
  :user_name: 'username'
  :password: 'password'

:production:
  :base_key: ''
  :host: '127.0.0.1'
  :port: 2379
  :user_name: 'username'
  :password: 'password'
```

While other tendrl components uses etcd instance referenced in `tendrl.conf` file (based on [etc/tendrl/tendrl.conf.sample](https://github.com/Tendrl/common/blob/master/etc/tendrl/tendrl.conf.sample) from tendrl-common):

```
[common]

# Central store etcd port
etcd_port = 2379

# Central store etcd host/ip
etcd_connection = 0.0.0.0
```

Would it make sense to unify the configuration of etcd instance so that one doesn't have to specify the same values multiple times? Or is there some reason for having different etcd instances for tendrl-api compared to other components?

**Comment by brainfunked** [comment]
The current format of the configuration file for the API is a standard way of doing configuration in ruby applications. I would suggest that it be kept as it is.

**Comment by r0h4n** [comment]
I dont see any updates to this, the current way of handling configuration files seems to be alright, lets mov on
