### ISSUE TITLE
tendrl-api service cleanup when rpm package is removed

### ISSUE THREAD

**Issue by dahorak** [Tendrl/api#378]
Un-installation process of tendrl-api package doesn't clean up systemd services.

Pre/post un-installation scripts should stop and disable all related services (tendrl-api in this case) and reload systemd.

As an example, please check following part from httpd.spec file:
```
%post
%systemd_post httpd.service htcacheclean.service

%preun
%systemd_preun httpd.service htcacheclean.service

%postun
%systemd_postun
```

**Comment by shirshendu** [comment]
@dahorak can we close this?

**Comment by dahorak** [comment]
Let me try the scenario from https://github.com/Tendrl/tendrl-ansible/issues/83, if it will works, we can close this issue.

**Comment by dahorak** [comment]
I've tried the scenario from https://github.com/Tendrl/tendrl-ansible/issues/83 and it is fixed in the latest package from master (`tendrl-api-1.6.0-20180306T115141.3b74256.noarch`), so closing this issue.
