### ISSUE TITLE
Repository name changes

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/api#38]
Repository names need to be updated to follow lowercase, hyphenated convention. In this case need to drop the tendrl prefix

**Comment by nthomas-redhat** [comment]
[](https://github.com/Tendrl/specifications/pull/24)

**Comment by nthomas-redhat** [comment]
https://github.com/Tendrl/specifications/pull/24

**Comment by r0h4n** [comment]
@Tendrl/tendrl_api Please finish this task on highest priority (cc @anivargi )
