### ISSUE TITLE
API call to trigger ExpandClusterWithDetectedPeers flow

### ISSUE THREAD

**Issue by shirshendu** [Tendrl/api#385]
As per https://github.com/Tendrl/commons/issues/805#issuecomment-371157440 , we need an API call that can enqueue a job that triggers the `ExpandClusterWithDetectedPeers` flow.
https://github.com/Tendrl/commons/pull/831/files#diff-1a5320aa0fd1eea178e6ed255509c9c4 holds definitions required for the spec.

**Comment by shirshendu** [comment]
There is also another existing (undocumented?) API '/:cluster_id/ExpandCluster`, which I'm assuming is in the old format.
That uses a flow called 'ExpandCluster', and needs node details (which are already available on the page with the expand cluster button).
I would like to remove it; is this API still in use? What are the scenarios? @Tendrl/frontend @Tendrl/ux

**Comment by shirshendu** [comment]
Tendrl/ui/issues/848 depends on this

**Comment by r0h4n** [comment]
@shirshendu The flow "ExpandCluster" was coded as a day 0 flow. Where it would actually install gluster on the new nodes using gdeploy and adds them to the Gluster trusted storage pool

The current "ExpandClusterWithDetectedPeers" simply detects new nodes which are recently added to the Gluster trusted storage pool by the user, it does not install gluster on the new nodes and assumes it is done by the user.

The old "ExpandCluster" flow is already disabled via definitions, the API can use that to decide if it is a valid flow or not
Check: https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/definition/master.yaml#L38
