### ISSUE TITLE
hosts alerts number

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#387]
API `nodes` call are not always returning number of alerts per node, only when some alert happens for the node. That leads to situation when UI says `No Data`. Which is correct from UI perspective because there really are no data. However as monitoring software we are aware how many alerts we got. So proper behavior for API will be to report 0 alerts in the case when no alert comes at all.

Tendrl version:
tendrl-api-1.6.1-1.el7.centos.noarch

**Comment by shirshendu** [comment]
This value is not set by tendrl-api. We simply show whatever is present in the database for the `alert_counters` attribute for a node. The right place to set this to `0` would probably be https://github.com/Tendrl/commons/search?utf8=%E2%9C%93&q=alert_counters&type=
@r0h4n @shtripat Thoughts?

**Comment by ltrilety** [comment]
After a discussion moving this to monitoring-integration component https://github.com/Tendrl/monitoring-integration/issues/374
