### ISSUE TITLE
API returning 500 error for `start_profiling` API call

### ISSUE THREAD

**Issue by gnehapk** [Tendrl/api#392]
Request data - 
`{"Volume.volname":"test-v1","Volume.vol_id":"3199b12f-0626-44ea-9315-03614a595e90"}`

Response - `{"errors":{"message":"Internal server error"}}`

**Comment by shirshendu** [comment]
Please provide more detail on the path and method of your API call.

**Comment by shirshendu** [comment]
The API is at `POST /clusters/:id/volumes/:volume_id/start_profiling`. With the fix in #398, we do not need any data in the body.
