### ISSUE TITLE
API to get the details of the ceph/gluster cluster

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/api#40]
Currently to import a cluster, user expected to provide the all the nodes in the cluster as input. This will be inconvenient if the size of the cluster is large. Instead the usecase flow is expected to be modified as:

select one of the node in cluster
use the selected node to get the details of the cluster
submit the request to all the nodes to import the cluster

Below APIs are requested:
GET /1.0/GlusterClusterDetails

Sample Request:

{
    "Node":"027db80d-eee9-40b6-8e59-8c81b80aa655"
}

Sample Response:

{
"peers": [{
        "fqdn": "dhcp43-44.lab.eng.blr.redhat.com",
        "machine_id": "6406e485f01347f4884bf6e1981020b7",
        "node_id": "194c4e0b-2541-4227-a808-358a3898f3c6"
        }]
"Tendrl_context.sds_name": "gluster",
"Tendrl_context.sds_version": "3.8.3"
}

GET /1.0/CephClusterDetails

Sample Request:

{
    "Node":"027db80d-eee9-40b6-8e59-8c81b80aa655"
}

Sample Response:

{
"servers": [{
        "fqdn": "dhcp43-44.lab.eng.blr.redhat.com",
        "machine_id": "6406e485f01347f4884bf6e1981020b7",
        "node_id": "194c4e0b-2541-4227-a808-358a3898f3c6"
        }]
"Tendrl_context.sds_name": "ceph",
"Tendrl_context.sds_version": "10.2.3"
}

**Comment by mkudlej** [comment]
I think that there should be also ID of Ceph/Gluster cluster in response. Because User should be able to identify cluster(from Ceph or Glsuter perspective). For example in case of Ceph it is **cluster name** and **cluster ID**.

**Comment by nthomas-redhat** [comment]
https://github.com/Tendrl/specifications/pull/60
