### ISSUE TITLE
Alerts which is displayed in UI is not for specific cluster, it is actually alerts of all clusters

### ISSUE THREAD

**Issue by GowthamShanmugam** [Tendrl/api#409]
I saw API request for alerts is HTTP://{ip}/api/1.0/alerts, and API giving alerts of all clusters.

This is actually wrong, the API request for alerts should be like http://10.70.43.245/api/1.0/alerts/{cid}
Then API should fetch cluster alerts from /alerting/clusters/{cid}/{here all alerts present for particular cluster}
also, find node alerts for that particular cluster. Find node ids for that cluster first and fetch alerts from 
/alerting/nodes/{nid}/ {all node alert for that particular node}.

Combine cluster_alerts + all node alerts for that particular cluster and send as single JSON to UI

**Comment by GowthamShanmugam** [comment]
@shtripat @shirshendu

**Comment by shirshendu** [comment]
API is already fetching details for a particular cluster. Please see https://github.com/Tendrl/api/blob/d706db396680f6fb0dcd80cb48078bdc4f3e68eb/app/controllers/alerting_controller.rb#L17

In my opinion, UI can do some data compilation from multiple API calls (cluster alerts and node alerts)  to show it in a certain way. That was the whole point of keeping UI and API separate. Else we could just be building a web app.
Building weird aggregation logic into a resource listing endpoint is not a good idea. Let us keep node and cluster 
@r0h4n @shtripat I'll be closing this unless you feel it is necessary. Thoughts?

**Comment by GowthamShanmugam** [comment]
But i saw UI is only passing http://{ip}/api/1.0/alerts api request only, @gnehapk please check this. 
Also, one more doubt is i saw node alert for api https://github.com/Tendrl/api/blob/d706db396680f6fb0dcd80cb48078bdc4f3e68eb/app/controllers/alerting_controller.rb#L21, But we can separate this alert cluster-wise and display in UI?

**Comment by GowthamShanmugam** [comment]
The alert api for a particular cluster should give cluster_alert + node_alert for the particular cluster in single JSON.

**Comment by GowthamShanmugam** [comment]
@shirshendu I also discussed this with @nthomas-redhat told like alerts list panel is global so I should display all alerts.

I think me misunderstood this, So i am fine with existing flow

**Comment by shirshendu** [comment]
Closing because query was resolved.
