### ISSUE TITLE
[systemd] name of systemd service should be "tendrl-api" instead of "tendrl-apid"

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/api#45]
The current name of systemd service for tendrl-api is `tendrl-apid` (note the `d` in the end). Wouldn't be better to use the same name for tendrl component, it's package and it's systemd service?

**Comment by mbukatov** [comment]
Similar issues filed for other components:

* https://github.com/Tendrl/gluster-integration/issues/107
* https://github.com/Tendrl/ceph-integration/issues/77

**Comment by anmolsachan** [comment]
PR #49 already there .. Already has intended changes.

**Comment by anivargi** [comment]
@mbukatov

**Comment by mbukatov** [comment]
@anivargi I see that the issue was fixed for tendrl-api back in December, but the request was not yet merged.

**Comment by mbukatov** [comment]
I need to recheck this ... I just installed upstream `tendrl-api-1.3.0-1.el7.centos.noarch` and the service is still called `tendrl-apid` ... why is this stalled?

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/api/pull/196

**Comment by mbukatov** [comment]
Thank you. I see this fixed in `tendrl-api-1.4.0-1.el7.centos.noarch`.
