### ISSUE TITLE
Do not generate cluster id for failed import gluster cluster job

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#50]
Api creates job when calling `POST` `GlusterImportCluster` with incorrect JSON data. After finishing this job there is in etcd `Status: finished` and generated `cluster_id`. but cluster with given `cluster_id` doesn't exist. There shouldn't be any `cluster_id` and job should be labeled as failed when job fails.

**Comment by anivargi** [comment]
@fbalak I don't understand what the issue is exactly, you only need to care about the clusters present in the clusters list. 
Currently when a job fails it is marked as failed. @r0h4n can you please elaborate.

**Comment by r0h4n** [comment]
Please confirm if this still exists

**Comment by fbalak** [comment]
@r0h4n `TendrlContext.integration_id` is still among items in `parameters` attribute of failed jobs but maybe it isn't a problem. @mbukatov @mkudlej What do you think?

**Comment by r0h4n** [comment]
Irrespective of whether the Create/Import job "finished", TendrlContext.integration_id is created by the API and is required during these flows. 

If the above flows "finished", you will see results at /clusters/$TendrlContext.integration_id 

else you wont see it, which is expected behaviour

**Comment by mbukatov** [comment]
As long as the results in `/clusters/$TendrlContext.integration_id` matches the results of the job and there is no `cluster_id` passed for failed cluster import job, it seems ok.
