### ISSUE TITLE
Calling GlusterStopVolume api call doesn't work

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#56]
When calling `https://hostname/api/:cluster_id:/GlusterStopVolume` specified by `https://hostname/api/:cluster_id:/Flows` server returns `job_id`. After processing of job is complete, nothing happens. This method should be finished.

**Comment by anivargi** [comment]
@fbalak please close if this is not a issue anymore.

**Comment by anivargi** [comment]
@fbalak

**Comment by fbalak** [comment]
@anivargi I will test it after issues related importing and creating cluster are resolved.
