### ISSUE TITLE
RPM : tendrl-api-httpd and tendrl-api-doc are not available on copr

### ISSUE THREAD

**Issue by nthomas-redhat** [Tendrl/api#66]
Above mentioned packages needs to be built.
Also tendrl-api-httpd to be added as a dependency to tendrl-dashboard

**Comment by TimothyAsir** [comment]
tendrl-api-httpd and tendrl-api-doc are subpackages for tendrl-api. These packages are build along with tendrl-api. Please check the link for reference https://copr-be.cloud.fedoraproject.org/results/tendrl/tendrl/epel-7-x86_64/00505944-tendrl-api/

Hope we can close this issue.

**Comment by nthomas-redhat** [comment]
@TimothyAsir Does https://github.com/Tendrl/dashboard/issues/118  taken care?

**Comment by sankarshanmukhopadhyay** [comment]
@TimothyAsir if this is sorted, please close the issue.
