### ISSUE TITLE
Deleting gluster volume via api doesn't change records in etcd

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#78]
When `DELETE` `hostname/api/1.0/cluster_id/GlusterDeleteVolume` request with appropriate data [1] is sent there is no change in records that can be obtained via `GetVolumeList` api call but gluster volume on nodes is deleted. Record with deleted volume should be deleted from etcd.
Job with `job_id` obtained from `GlusterDeleteVolume` api call is also never finished. Status of job is still `processing`. Should be `finished`.
Tested with:
tendrl-api-1.2-02_08_2017_01_51_04.noarch
tendrl-gluster-integration-1.2-02_08_2017_04_38_03.noarch
tendrl-commons-1.2-02_08_2017_04_42_04.noarch
tendrl-node-agent-1.2-02_08_2017_00_01_03.noarch

[1] https://github.com/Tendrl/api/blob/master/docs/volumes.adoc#delete-volume

**Comment by r0h4n** [comment]
Fixed: https://github.com/Tendrl/gluster-integration/commit/b319c4ffc0251a24389d757c5298da252d725cb3

Please try to reproduce

**Comment by fbalak** [comment]
As of now the issue cannot be reproduced, it's blocked by https://github.com/Tendrl/api/issues/82

**Comment by sankarshanmukhopadhyay** [comment]
Now that https://github.com/Tendrl/api/issues/82 is closed - can we circle back to the topic and validate the fix?

**Comment by anivargi** [comment]
@fbalak please comment or close the issue.

**Comment by fbalak** [comment]
@anivargi I think I saw it fixed but I will test it more after https://github.com/Tendrl/api/issues/91 is resolved.

**Comment by anivargi** [comment]
Why is this dependent upon #91 to be fixed?

**Comment by anivargi** [comment]
@fbalak can you verify and close.

**Comment by fbalak** [comment]
@anivargi I will test this and probably close it after https://github.com/Tendrl/api/issues/94 will be resolved.

**Comment by sankarshanmukhopadhyay** [comment]
#94 was blocked by #99 which is now resolved - can we get around to verifying this?

**Comment by mkudlej** [comment]
https://github.com/Tendrl/api/issues/94 is not fixed.

**Comment by sankarshanmukhopadhyay** [comment]
Now that https://github.com/Tendrl/api/issues/94 is closed, please verify this and provide us with feedback.

**Comment by mkudlej** [comment]
I'll wait for resolving of https://github.com/Tendrl/api/issues/91 Then we can create and delete volume via API and check Etcd record.

**Comment by fbalak** [comment]
After API call the volume is deleted from etcd. Looks ok. --> closing
Tested with:
tendrl-performance-monitoring-1.2.3-04_25_2017_03_02_03.noarch
tendrl-api-1.2.3-04_25_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-04_25_2017_00_01_05.noarch
tendrl-node-monitoring-1.2.3-04_25_2017_04_25_04.noarch
tendrl-gluster-integration-1.2.3-04_25_2017_04_39_18.noarch
tendrl-commons-1.2.3-04_25_2017_17_15_13.noarch
