### ISSUE TITLE
GetNodeList called on a cluster

### ISSUE THREAD

**Issue by ltrilety** [Tendrl/api#80]
`<hostname>/api/1.0/<cluster_id>/GetNodeList` API get call return status is `200 OK` however it returns always empty list.

Sample Request
```
curl -XGET http://ltrilety-usm5-server.usmqe.lab.eng.brq.redhat.com/api/1.0/44ab712e-9ddb-4b9a-89f2-84e20a90254b/GetNodeList
```

Sample Response
```
Status: 200 OK
[]
```

Seen on:
tendrl-api-1.2-02_08_2017_01_51_04.noarch
tendrl-api-httpd-1.2-02_08_2017_01_51_04.noarch

**Comment by anivargi** [comment]
@ltrilety there is no such documented API, where are you referring the API call from?

**Comment by ltrilety** [comment]
@anivargi probably I just thought to be logical to have such API call or I got it from `Flows` API call which was then. Anyway the call exists as it returns `200 OK`. So as I see it, the call should be removed or corrected to work properly.

**Comment by anivargi** [comment]
@ltrilety List calls are never exposed in `Flows`. 
Added a PR https://github.com/Tendrl/api/pull/93 to handle case where user requests list for unknown/undocumented object. Will return 404.

**Comment by anivargi** [comment]
@ltrilety can you verify and close this?

**Comment by ltrilety** [comment]
@anivargi sorry I can't at least for now, I am blocked by https://github.com/Tendrl/api/issues/94

**Comment by ltrilety** [comment]
Now it returns `404 Not Found`

Checked with:
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-node-monitoring-1.2.1-04_05_2017_11_26_13.noarch
