### ISSUE TITLE
Format of URLs of API calls are not unified

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#81]
URLs of all API calls except `hostname/api/1.0/jobs`, `hostname/api/1.0/ping` and `hostname/api/1.0/monitoring/*` start with Uppercase. These three start with Lowercase. URLs of API calls should be unified (all start with Uppercase) or case insensitive.

**Comment by mbukatov** [comment]
I have added this issue into [Proposed Release Blockers](https://github.com/Tendrl/usmqe-tests/wiki#proposed-release-blockers), cost of fixing this bug is going to be much higher if we let it unfixed.

**Comment by mbukatov** [comment]
Why was this closed? Btw last week, @anivargi told me that we plan to fix issues such as https://github.com/Tendrl/documentation/issues/70 so I don't see any reason not to include this one in the polishing as well
