### ISSUE TITLE
ImportCluster API call with already imported nodes creates empty cluster

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#88]
I have imported Gluster cluster in Tendrl with certain nodes. When I call `ImportCluster` API call again with those nodes that are already imported, there is created a new cluster in Tendrl with no hosts. Job related to this action should fail and there shouldn't be imported any cluster (only the original one).

Tested with:
tendrl-api-1.2.1-03_02_2017_01_51_02.noarch
tendrl-node-agent-1.2.1-03_02_2017_00_01_02.noarch
tendrl-gluster-integration-1.2.1-03_02_2017_04_38_02.noarch

**Comment by anivargi** [comment]
@r0h4n @shtripat What is the expected behaviour here?

**Comment by shtripat** [comment]
If cluster with same name already exists in tendrl central store, certainly the flow should error out. I feel there should a pre check added to import cluster flow.

**Comment by r0h4n** [comment]
Is this still reproducible?

**Comment by fbalak** [comment]
Importing cluster with already imported nodes fails. --> closing
Tested with:
tendrl-api-1.2.1-04_04_2017_01_51_03.noarch
tendrl-commons-1.2.1-04_01_2017_00_59_17.noarch
tendrl-node-agent-1.2.2-04_04_2017_00_01_04.noarch
tendrl-gluster-integration-1.2.1-04_04_2017_04_38_03.noarch
