### ISSUE TITLE
GetClusterList API call without imported cluster returns `404 not found`

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#89]
When I call `hostname/api/1.0/GetClusterList` without any imported cluster I get `404 not found` response. This API call works fine when Gluster cluster is imported. API call `hostname/api/1.0/GetClusterList` should return empty json (or at least some response) when there is no imported cluster.
I think that this issue also breaks UI where it displays `Server not found (404) !` on front page and doesn't display `import cluster` option selection.

Tested with:
tendrl-api-1.2.1-03_02_2017_01_51_02.noarch
tendrl-dashboard-1.2.1-03_02_2017_12_19_25.noarch
tendrl-performance-monitoring-1.2.1-03_02_2017_03_02_02.noarch
tendrl-commons-1.2.1-2.el7.centos.noarch
tendrl-node-agent-1.2.1-03_02_2017_00_01_02.noarch

**Comment by anivargi** [comment]
@fbalak Fix is on https://github.com/Tendrl/api/pull/92, it has been merged so should be available as a build once the job is triggered.
