### ISSUE TITLE
GlusterCreateVolume API call doesn't work

### ISSUE THREAD

**Issue by fbalak** [Tendrl/api#91]
When I call `hostname/api/1.0/cluster_id/GlusterCreateVolume` according to https://github.com/Tendrl/api/blob/d3b44bbd8f85f545e112f0fae781fed3b366d3c2/docs/volumes.adoc I get `job_id` in response but the job is never finished. It remains `processing` and there is no volume created. Job should finish and there should be created Gluster volume.

Tested with:
tendrl-api-1.2.1-03_02_2017_01_51_02.noarch
tendrl-node-agent-1.2.1-03_02_2017_00_01_02.noarch
tendrl-gluster-integration-1.2.1-03_02_2017_04_38_02.noarch

**Comment by anivargi** [comment]
@fbalak please provide details like the payload that was sent to the request.

**Comment by fbalak** [comment]
@anivargi I posted this json `{"Volume.volname": "Vol_test", "Volume.bricks": ["hostname-node1:/bricks/fs_gluster01/brick", "hostname-node2:/bricks/fs_gluster01/brick", "hostname-node3:/bricks/fs_gluster01/brick", "hostname-node4:/bricks/fs_gluster01/brick"]}`. Cluster was already imported and directories for bricks exist.

**Comment by anivargi** [comment]
@shtripat can you verify why it is stuck on `processing`?

**Comment by shtripat** [comment]
@fbalak can you share the `/var/log/tendrl/gluster-integration/gluster-integration_info.log`

If there is some error in the log, that might give you clue as well. Also `cluster/{id}/_jobs/{job_id}` would also give some clue what all has happened while running the flow for volume creation.

**Comment by fbalak** [comment]
@shtripat 
`/var/log/tendrl/gluster-integration/gluster-integration_info.log`:
`2017-03-03T13:34:48+0000 - /usr/lib/python2.7/site-packages/tendrl/gluster_integration/sds_sync/__init__.py - __init__.py:235 -                 _run() - ERROR - Raft Internal Error : etcdserver: request timed out`

And this is content of `hostname:2379/v2/keys/clusters/0381837b-3806-4eea-8c05-d54bb773f62a/_jobs/tendrl.gluster_integration.flows.create_volume.CreateVolume_e7be683a-b784-4226-aa61-7f88b3efb4bb`:
`{"action":"get","node":{"key":"/clusters/0381837b-3806-4eea-8c05-d54bb773f62a/_jobs/tendrl.gluster_integration.flows.create_volume.CreateVolume_ae7db2ed-46b2-42f3-bf68-f70ef8356fa4","dir":true,"nodes":[{"key":"/clusters/0381837b-3806-4eea-8c05-d54bb773f62a/_jobs/tendrl.gluster_integration.flows.create_volume.CreateVolume_ae7db2ed-46b2-42f3-bf68-f70ef8356fa4/00000000000000051667","value":"{\"publisher\": \"gluster_integration\", \"timestamp\": \"2017-03-03T10:39:15.185799+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 18, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Starting creation flow for volume Vol_test\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"23ef3eab-c21d-4867-9ef0-3f29d32383ef\", \"cluster_id\": \"0381837b-3806-4eea-8c05-d54bb773f62a\", \"request_id\": \"clusters/0381837b-3806-4eea-8c05-d54bb773f62a/_jobs/tendrl.gluster_integration.flows.create_volume.CreateVolume_ae7db2ed-46b2-42f3-bf68-f70ef8356fa4\", \"flow_id\": \"1951e821-7aa9-4a91-8183-e73bc8275b8e\", \"message_id\": \"d7d6ac94-f0ac-4460-8cae-7c1aa8135f88\"}","modifiedIndex":51667,"createdIndex":51667},{"key":"/clusters/0381837b-3806-4eea-8c05-d54bb773f62a/_jobs/tendrl.gluster_integration.flows.create_volume.CreateVolume_ae7db2ed-46b2-42f3-bf68-f70ef8356fa4/00000000000000051668","value":"{\"publisher\": \"gluster_integration\", \"timestamp\": \"2017-03-03T10:39:15.362105+00:00\", \"caller\": {\"function\": \"run\", \"line_no\": 23, \"filename\": \"__init__.py\"}, \"payload\": {\"message\": \"Checking if volume Vol_test doesnt exist\"}, \"priority\": \"info\", \"parent_id\": null, \"node_id\": \"23ef3eab-c21d-4867-9ef0-3f29d32383ef\", \"cluster_id\": \"0381837b-3806-4eea-8c05-d54bb773f62a\", \"request_id\": \"clusters/0381837b-3806-4eea-8c05-d54bb773f62a/_jobs/tendrl.gluster_integration.flows.create_volume.CreateVolume_ae7db2ed-46b2-42f3-bf68-f70ef8356fa4\", \"flow_id\": \"1951e821-7aa9-4a91-8183-e73bc8275b8e\", \"message_id\": \"e44016f1-36f2-4494-a583-4b83269ee10d\"}","modifiedIndex":51668,"createdIndex":51668}],"modifiedIndex":51667,"createdIndex":51667}}
`

**Comment by shtripat** [comment]
Looks like connectivity issue with etcd server. Plz check if etcd server is up and running and details are correct in conf files. I will try to simulate in my own setup as well...

**Comment by fbalak** [comment]
@shtripat I hope this helps.
On server node:
`# systemctl status etcd`
● etcd.service - Etcd Server
   Loaded: loaded (/usr/lib/systemd/system/etcd.service; enabled; vendor preset: disabled)
   Active: active (running) since Fri 2017-03-03 10:09:50 UTC; 4h 40min ago
 Main PID: 19708 (etcd)
   CGroup: /system.slice/etcd.service
           └─19708 /usr/bin/etcd --name=default --data-dir=/var/lib/etcd/default.etcd --listen-client-urls=http://hostname:2379

```
Mar 03 14:38:13 hostname etcd[19708]: compacted raft log at 545097
Mar 03 14:38:20 hostname etcd[19708]: purged file /var/lib/etcd/default.etcd/member/snap/0000000000000002-000000000007a17c.snap successfully
Mar 03 14:42:56 hostname etcd[19708]: start to snapshot (applied: 560098, lastsnap: 550097)
Mar 03 14:42:56 hostname etcd[19708]: saved snapshot at index 560098
Mar 03 14:42:56 hostname etcd[19708]: compacted raft log at 555098
Mar 03 14:43:20 hostname etcd[19708]: purged file /var/lib/etcd/default.etcd/member/snap/0000000000000002-000000000007c88d.snap successfully
Mar 03 14:47:26 hostname etcd[19708]: start to snapshot (applied: 570099, lastsnap: 560098)
Mar 03 14:47:27 hostname etcd[19708]: saved snapshot at index 570099
Mar 03 14:47:27 hostname etcd[19708]: compacted raft log at 565099
Mar 03 14:47:50 hostname etcd[19708]: purged file /var/lib/etcd/default.etcd/member/snap/0000000000000002-000000000007ef9e.snap successfully
```

`# journalctl _PID=19708`
```
-- Logs begin at Fri 2017-03-03 09:54:27 UTC, end at Fri 2017-03-03 14:50:55 UTC. --
Mar 03 10:09:50 hostname etcd[19708]: recognized and used environment variable ETCD_ADVERTISE_CLIENT_URLS=hostname
Mar 03 10:09:50 hostname etcd[19708]: recognized and used environment variable ETCD_LISTEN_PEER_URLS=http://hostname:238
Mar 03 10:09:50 hostname etcd[19708]: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
Mar 03 10:09:50 hostname etcd[19708]: recognized environment variable ETCD_DATA_DIR, but unused: shadowed by corresponding flag 
Mar 03 10:09:50 hostname etcd[19708]: recognized environment variable ETCD_LISTEN_CLIENT_URLS, but unused: shadowed by corresponding flag 
Mar 03 10:09:50 hostname etcd[19708]: expected IP in URL for binding (http://hostname:2380)
Mar 03 10:09:50 hostname etcd[19708]: expected IP in URL for binding (http://hostname:2379)
Mar 03 10:09:50 hostname etcd[19708]: etcd Version: 3.0.15
Mar 03 10:09:50 hostname etcd[19708]: Git SHA: fc00305
Mar 03 10:09:50 hostname etcd[19708]: Go Version: go1.6.3
Mar 03 10:09:50 hostname etcd[19708]: Go OS/Arch: linux/amd64
Mar 03 10:09:50 hostname etcd[19708]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Mar 03 10:09:50 hostname etcd[19708]: listening for peers on http://hostname:2380
Mar 03 10:09:50 hostname etcd[19708]: listening for client requests on hostname:2379
Mar 03 10:09:50 hostname etcd[19708]: name = default
Mar 03 10:09:50 hostname etcd[19708]: data dir = /var/lib/etcd/default.etcd
Mar 03 10:09:50 hostname etcd[19708]: member dir = /var/lib/etcd/default.etcd/member
Mar 03 10:09:50 hostname etcd[19708]: heartbeat = 100ms
Mar 03 10:09:50 hostname etcd[19708]: election = 1000ms
Mar 03 10:09:50 hostname etcd[19708]: snapshot count = 10000
Mar 03 10:09:50 hostname etcd[19708]: advertise client URLs = http://hostname:2379
Mar 03 10:09:50 hostname etcd[19708]: initial advertise peer URLs = http://localhost:2380
Mar 03 10:09:50 hostname etcd[19708]: initial cluster = default=http://localhost:2380
Mar 03 10:09:50 hostname etcd[19708]: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
Mar 03 10:09:50 hostname etcd[19708]: 8e9e05c52164694d became follower at term 0
Mar 03 10:09:50 hostname etcd[19708]: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
Mar 03 10:09:50 hostname etcd[19708]: 8e9e05c52164694d became follower at term 1
Mar 03 10:09:50 hostname etcd[19708]: starting server... [version: 3.0.15, cluster version: to_be_decided]
Mar 03 10:09:50 hostname etcd[19708]: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
Mar 03 10:09:50 hostname etcd[19708]: 8e9e05c52164694d is starting a new election at term 1
Mar 03 10:09:50 hostname etcd[19708]: 8e9e05c52164694d became candidate at term 2
Mar 03 10:09:50 hostname etcd[19708]: 8e9e05c52164694d received vote from 8e9e05c52164694d at term 2
Mar 03 10:09:50 hostname etcd[19708]: 8e9e05c52164694d became leader at term 2
Mar 03 10:09:50 hostname etcd[19708]: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 2
Mar 03 10:09:50 hostname etcd[19708]: setting up the initial cluster version to 3.0
Mar 03 10:09:50 hostname etcd[19708]: set the initial cluster version to 3.0
Mar 03 10:09:50 hostname etcd[19708]: enabled capabilities for version 3.0
Mar 03 10:09:50 hostname etcd[19708]: published {Name:default ClientURLs:[http://hostname:2379]} to cluster cdf818194e3a
Mar 03 10:09:50 hostname etcd[19708]: ready to serve client requests
Mar 03 10:09:50 hostname etcd[19708]: serving insecure client requests on hostname:2379, this is strongly discouraged!
Mar 03 10:10:17 hostname etcd[19708]: sync duration of 1.444250701s, expected less than 1s
Mar 03 10:10:19 hostname etcd[19708]: sync duration of 1.521692899s, expected less than 1s
Mar 03 10:10:29 hostname etcd[19708]: sync duration of 1.011117798s, expected less than 1s
Mar 03 10:10:31 hostname etcd[19708]: sync duration of 1.593346269s, expected less than 1s
Mar 03 10:12:47 hostname etcd[19708]: sync duration of 1.413122578s, expected less than 1s
Mar 03 10:13:28 hostname etcd[19708]: sync duration of 2.598795934s, expected less than 1s
Mar 03 10:13:31 hostname etcd[19708]: sync duration of 2.278081202s, expected less than 1s
Mar 03 10:14:56 hostname etcd[19708]: sync duration of 1.387882926s, expected less than 1s
Mar 03 10:15:11 hostname etcd[19708]: sync duration of 1.111710305s, expected less than 1s
Mar 03 10:16:45 hostname etcd[19708]: apply entries took too long [10.420633ms for 1 entries]
```

On storage node:
`# cat /etc/tendrl/node-agent/node-agent.conf.yaml `
```
---
etcd_port: 2379
etcd_connection: hostname
tendrl_ansible_exec_file: $HOME/.tendrl/node-agent/ansible_exec
log_cfg_path: /etc/tendrl/node-agent/node-agent_logging.yaml
log_level: DEBUG
package_source_type: rpm
logging_socket_path: /var/run/tendrl/message.sock
```

**Comment by shtripat** [comment]
@fbalak I tried locally in my setup using API and it works fine.
Looking at `/etc/tendrl/node-agent/node-agent.conf.yaml` this certainly looks problematic as the value of `etcd_connection` should be IP of the node where etcd server is running.
Correct the same and also check and correct the value in `/etc/tendrl/gluster-integration/gluster-integration.conf.yaml` (if wrong). After this you need to re-start `tendrl-node-agent` and `tendrl-gluster-integration`.
It should ideally work post these changes ...

**Comment by sankarshanmukhopadhyay** [comment]
This is listed under https://github.com/Tendrl/usmqe-tests/wiki#blockers @fbalak please update if you have been able to adopt the suggestion from Shubhendu.

**Comment by sankarshanmukhopadhyay** [comment]
Have we made progress on this? The chain of blockers around the topic seem to have been resolved.

**Comment by mkudlej** [comment]
Cannot test this because of https://github.com/Tendrl/api/issues/94

**Comment by fbalak** [comment]
Job failed when I tried to reproduce it. This is content of etcd call:
`{"action":"get","node":{"key":"/queue/bb1dc44d-450e-40bd-a749-ee8e9ce1bddc/errors","value":"Error executing atom: tendrl.objects.Node.atoms.Cmd on flow: Execute given command on given node","modifiedIndex":715,"createdIndex":715}}`
Tested with:
tendrl-api-1.2.1-04_03_2017_01_51_03.noarch
tendrl-performance-monitoring-1.2.1-04_03_2017_13_14_13.noarch
tendrl-commons-1.2.1-04_01_2017_00_59_17.noarch

**Comment by mkudlej** [comment]
This bug seems still there 
```
$ etcdctl --endpoints=http://${HOSTNAME}:2379 get /queue/1c575f5d-e0ba-43a0-b051-9db21f489e7b/errors
global name 'create_gluster_volume' is not defined
```
```
etcd-3.1.0-2.el7.x86_64
python-etcd-0.4.3-1.noarch
rubygem-etcd-0.3.0-1.el7.centos.noarch
tendrl-api-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-doc-1.2.1-04_05_2017_01_51_04.noarch
tendrl-api-httpd-1.2.1-04_05_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_05_2017_04_42_03.noarch
tendrl-dashboard-1.2.1-04_05_2017_11_03_12.noarch
tendrl-node-agent-1.2.2-04_05_2017_00_01_04.noarch
tendrl-performance-monitoring-1.2.1-04_05_2017_11_26_14.noarch
```

**Comment by sankarshanmukhopadhyay** [comment]
A quick clarifying question - the v1.2.2 build did not declare any Gluster features being signed off as integration testing completed - do we want to wait until dev signs off on these?

**Comment by mkudlej** [comment]
@sankarshanmukhopadhyay I think this worked before, so it is regression.

**Comment by fbalak** [comment]
When I try to create volume according to https://github.com/Tendrl/api/blob/master/docs/volumes.adoc#create-volume the job fails but now there is a message on address hosntame/api/1.0/jobs/job_id/messages: `Invalid JSON received.` Was there some change in volume creation flow or added some mandatory parameter?

Tested with:
tendrl-performance-monitoring-1.2.2-04_13_2017_03_02_03.noarch
tendrl-node-agent-1.2.2-04_13_2017_03_06_16.noarch
tendrl-api-1.2.2-04_13_2017_01_51_04.noarch
tendrl-commons-1.2.2-04_13_2017_04_42_04.noarch
tendrl-gluster-integration-1.2.2-04_13_2017_04_38_44.noarch

**Comment by nnDarshan** [comment]
The new structure for create volume is:

{"Volume.volname":"Volume_3","Volume.bricks":[[{"node1":"/glusterfs/b1_mount/b1"}, {"node2":"/glusterfs/b3_mount/b3"}],[{"node1":"/glusterfs/b2_mount/b2"}, {"node2":"/glusterfs/b4_mount/b4"}], [{"node3":"/glusterfs/b5_mount/b5"}, {"node4":"/glusterfs/b7_mount/b7"}]], "Volume.replica_count": "2", "Volume.force": true}

for brick list we have to provide list of list, where each sub list should contain details of bricks for a sub-volume. In above example there are 3 sub-volumes with each having 2 replica sets.

@anivargi  Could you please update the API doc accordingly

**Comment by anivargi** [comment]
@nnDarshan Ack.

**Comment by fbalak** [comment]
@nnDarshan I tried your example but it still returns message `Invalid JSON received.` I tried it with valid brick paths and as node1-4 I tried to use fqdn and node_id. All jobs failed.
Tested with:
tendrl-commons-1.2.2-04_17_2017_20_19_16.noarch
tendrl-node-agent-1.2.3-04_18_2017_02_22_22.noarch
tendrl-gluster-integration-1.2.3-04_18_2017_04_40_20.noarch
tendrl-performance-monitoring-1.2.2-04_18_2017_03_02_04.noarch
tendrl-api-1.2.2-04_18_2017_01_51_04.noarch

**Comment by nnDarshan** [comment]
@fbalak Could you please provide the API request body

**Comment by fbalak** [comment]
@nnDarshan POST {"Volume.volname":"Volume_3","Volume.bricks":[[{"8f0d7e28-0f12-4ac5-a95d-ebc6b436da40":"/bricks/fs_gluster01/brick"}, {"39f69de0-522d-42f7-bb2e-58b33bd4bb9e":"/bricks/fs_gluster01/brick"}],[{"8f0d7e28-0f12-4ac5-a95d-ebc6b436da40":"/bricks/fs_gluster01/brick"}, {"39f69de0-522d-42f7-bb2e-58b33bd4bb9e":"/bricks/fs_gluster01/brick"}], [{"dc5422c8-15a1-4e8d-96ad-4d1161d9054b":"/bricks/fs_gluster01/brick"}, {"ec98367b-a3fe-4cdc-84c9-95cdd41c1fc0":"/bricks/fs_gluster01/brick"}]], "Volume.replica_count": "2", "Volume.force": true} to http://hostname/api/1.0/971992be-375e-4ee3-a6fd-c66ff65c9210/GlusterCreateVolume
This is example with node_ids. I also tried using fqdn.

**Comment by anivargi** [comment]
@fbalak a curl command would be better, since we need to know how you are posting the data to the backend and receiving the invalid json response

**Comment by fbalak** [comment]
@anivargi ok:
`curl -H "Content-Type: application/json" -H "Authorization: Bearer 9ad50ee4c40a895e1865da0b9feb63c964e2de4fa552a384ff1c8636549df7ee" -X POST -d '{"Volume.volname":"Volume_3","Volume.bricks":[[{"hostname1":"/bricks/fs_gluster01/brick"}, {"hostname2":"/bricks/fs_gluster01/brick"}],[{"hostname1":"/bricks/fs_gluster02/brick"}, {"hostname2":"/bricks/fs_gluster02/brick"}], [{"hostname3":"/bricks/fs_gluster01/brick"}, {"hostname4":"/bricks/fs_gluster01/brick"}]], "Volume.replica_count": "2", "Volume.force": true}' http://hostname/api/1.0/971992be-375e-4ee3-a6fd-c66ff65c9210/GlusterCreateVolume`
where `hostname` is hostname of server where api is run and `hostname1-4` are fqdn of nodes.

**Comment by nnDarshan** [comment]
@fbalak There are a few changes(we are using gdeploy instead of cli calls) in the way gluster CRUD operations happen in latest release. As part of import/create cluster gdeploy is installed in one of the nodes and the environment needed for it is set up. So please try volume creation with newly created cluster / newly imported cluster.
The updated installation guide for installing packages is at: https://github.com/Tendrl/documentation/wiki/Tendrl-Package-Installation-Reference
Also, the updated API documentation for volume CRUD is at: https://github.com/Tendrl/api/blob/master/docs/volumes.adoc
Please use the latest packages from the release branch (with tag 1.2.3).

**Comment by fbalak** [comment]
@nnDarshan I added gdeploy repo according to documentation but job from curl command above still returns "message": "Invalid JSON received."
Tested with:
tendrl-commons-1.2.3-04_19_2017_05_13_06.noarch
tendrl-performance-monitoring-1.2.2-04_19_2017_03_02_04.noarch
tendrl-api-1.2.3-04_19_2017_01_51_04.noarch
tendrl-node-agent-1.2.3-04_19_2017_00_01_05.noarch
tendrl-node-monitoring-1.2.2-04_19_2017_04_25_04.noarch
tendrl-gluster-integration-1.2.3-04_19_2017_04_39_16.noarch

**Comment by nthomas-redhat** [comment]
@fbalak , please share the setup with us. I will send a separate email regrading this. This definitely not seen in our environment.

**Comment by fbalak** [comment]
Now it seems ok. --> closing

Tested with:
tendrl-api-1.2.3-04_20_2017_01_51_03.noarch
tendrl-node-agent-1.2.3-04_20_2017_00_01_06.noarch
tendrl-node-monitoring-1.2.3-04_20_2017_04_25_04.noarch
tendrl-gluster-integration-1.2.3-04_20_2017_04_39_21.noarch
tendrl-commons-1.2.3-04_20_2017_05_13_04.noarch
